In [13]:
## Getting data
!wget -O source.zip https://www.dropbox.com/s/dy8xyabnahh8onk/source.zip?dl=0
!unzip source.zip -d source

--2017-12-01 09:58:44--  https://www.dropbox.com/s/dy8xyabnahh8onk/source.zip?dl=0
Resolviendo www.dropbox.com (www.dropbox.com)... 162.125.5.1, 2620:100:601d:1::a27d:501
Conectando con www.dropbox.com (www.dropbox.com)[162.125.5.1]:443... conectado.
Petición HTTP enviada, esperando respuesta... 302 Found
Ubicación: https://dl.dropboxusercontent.com/content_link/7NjtGvkXuthKCTtz99NGE11ydSerSyDNMdnD3yaV6YiQFtOgA2uS1lZrSqnpcu1Y/file [siguiente]
--2017-12-01 09:58:45--  https://dl.dropboxusercontent.com/content_link/7NjtGvkXuthKCTtz99NGE11ydSerSyDNMdnD3yaV6YiQFtOgA2uS1lZrSqnpcu1Y/file
Resolviendo dl.dropboxusercontent.com (dl.dropboxusercontent.com)... 162.125.5.6, 2620:100:601d:6::a27d:506
Conectando con dl.dropboxusercontent.com (dl.dropboxusercontent.com)[162.125.5.6]:443... conectado.
Petición HTTP enviada, esperando respuesta... 200 OK
Longitud: 12141343 (12M) [application/zip]
Grabando a: “source.zip”

source.zip          100%[===================>]  11,58M   715KB/s    in 17s

2017-12-01 09:59:03 (700 KB/s) - “source.zip” guardado [12141343/12141343]

Archive:  source.zip
  inflating: source/almacenes.csv
  inflating: source/anticiposhotel.csv
  inflating: source/articulosbf.csv
  inflating: source/articulos.csv
  inflating: source/articulosda.csv
  inflating: source/asignaciondeduccion.csv
  inflating: source/bancos.csv
  inflating: source/bonosregalo.csv
  inflating: source/cantidadsinelaborar.csv
  inflating: source/capacidadoperaciones.csv
 extracting: source/caracteristicashabitacion.csv
  inflating: source/cargofijos.csv
  inflating: source/cargos.csv
  inflating: source/celulares.csv
 extracting: source/cencostos.csv
  inflating: source/chorario.csv
  inflating: source/ciudades.csv
 extracting: source/claseefectivo.csv
  inflating: source/clientes.csv
  inflating: source/comboscat.csv
  inflating: source/combos.csv
  inflating: source/consql.csv
  inflating: source/cree.csv
  inflating: source/ctasxcob.csv
  inflating: source/ctasxpag.csv
  inflating: source/cuentasbanco.csv
  inflating: source/cuentas.csv
  inflating: source/cuentasniif.csv
  inflating: source/depositos.csv
  inflating: source/descargamanualmateriaprima.csv
  inflating: source/descargamanualmateriaprimadetalle.csv
  inflating: source/detacont.csv
  inflating: source/detafacoa.csv
  inflating: source/detafaco.csv
  inflating: source/detafacoh.csv
  inflating: source/detafavea.csv
  inflating: source/detafave.csv
  inflating: source/detafaveh.csv
  inflating: source/detahotela.csv
  inflating: source/detahotel.csv
  inflating: source/detahotelh.csv
  inflating: source/detahotell.csv
  inflating: source/detahotels.csv
  inflating: source/detanomi.csv
  inflating: source/detareferenciaspersonalcomercial.csv
 extracting: source/diasfestivos.csv
 extracting: source/dimensiones.csv
  inflating: source/empresasoc.csv
  inflating: source/estados.csv
  inflating: source/estilos.csv
  inflating: source/gastos.csv
  inflating: source/grupos.csv
  inflating: source/gruposoperaciones.csv
  inflating: source/grupost.csv
  inflating: source/habitacionesh.csv
  inflating: source/ica.csv
  inflating: source/invpedproduccion.csv
  inflating: source/islr.csv
  inflating: source/iva.csv
  inflating: source/lineas.csv
  inflating: source/lotemaquila.csv
  inflating: source/maescc.csv
  inflating: source/maescont.csv
  inflating: source/maesfacoa.csv
  inflating: source/maesfaco.csv
  inflating: source/maesfacoh.csv
  inflating: source/maesfavea.csv
  inflating: source/maesfave.csv
  inflating: source/maesfaveh.csv
  inflating: source/maeshotel.csv
  inflating: source/maesnomi.csv
  inflating: source/mail.csv
  inflating: source/maquinarias.csv
  inflating: source/marcas.csv
  inflating: source/materiales.csv
  inflating: source/mesaspv.csv
  inflating: source/mnumeros.csv
 extracting: source/notaspv.csv
  inflating: source/numeros.csv
  inflating: source/operacionescif.csv
  inflating: source/operaciones.csv
  inflating: source/operacioneslineadeproduccion.csv
  inflating: source/paises.csv
  inflating: source/partidaspresupuestariasa.csv
  inflating: source/partidaspresupuestarias.csv
  inflating: source/partidaspresupuestariast.csv
  inflating: source/personalasignaciondeduccion.csv
  inflating: source/personal.csv
  inflating: source/personalprestamos.csv
 extracting: source/preciosdimensiones.csv
  inflating: source/preciosydimensiones.csv
  inflating: source/presupuestocostocif.csv
  inflating: source/presupuestocosto.csv
  inflating: source/presupuestocostooperacion.csv
  inflating: source/presupuestocostoseccion.csv
  inflating: source/procesos.csv
  inflating: source/procesosyoperacionescambios.csv
  inflating: source/procesosyoperaciones.csv
  inflating: source/producciongrupalcantidad.csv
  inflating: source/producciongrupal.csv
  inflating: source/producciongrupaloperacion.csv
  inflating: source/producciongrupalporcentaje.csv
 extracting: source/promociones.csv
  inflating: source/proveedores.csv
  inflating: source/recepcionparcialop.csv
  inflating: source/referencias.csv
  inflating: source/registrotareasproduccion.csv
  inflating: source/reportez.csv
  inflating: source/secciones.csv
  inflating: source/serialesa.csv
  inflating: source/seriales.csv
  inflating: source/serialesv.csv
  inflating: source/serviciosincluidos.csv
  inflating: source/serviciosincluidosdetalle.csv
  inflating: source/suboperaciones.csv
  inflating: source/tallas.csv
  inflating: source/tareasytickets.csv
  inflating: source/tareasyticketsh.csv
  inflating: source/tarifashabitacion.csv
  inflating: source/tipasientos.csv
  inflating: source/tipgastos.csv
 extracting: source/tiposhabitacion.csv
  inflating: source/tiposreservas.csv
  inflating: source/tipotransaccionesbanco.csv
  inflating: source/tmpdimensiones.csv
  inflating: source/tmpseriales.csv
  inflating: source/totseriales.csv
  inflating: source/transaccionescajaybancoscontab.csv
  inflating: source/transaccionescajaybancos.csv
 extracting: source/ubicaciongeograficahabitacion.csv
  inflating: source/unidades.csv
  inflating: source/usuarios.csv
  inflating: source/usuariosd.csv
  inflating: source/uvt.csv
  inflating: source/vales.csv
  inflating: source/zmsqactividad.csv
  inflating: source/zmsqetapacer.csv
  inflating: source/zmsqetapamet.csv
  inflating: source/zmsqfase.csv
  inflating: source/zmsqonp.csv
  inflating: source/zmsqproceso.csv
  inflating: source/zmsqsector.csv
  inflating: source/zmsqtic.csv
 extracting: source/zonas.csv

In [14]:
import pandas as pd

df = pd.read_csv('source/tareasytickets.csv')
df.head()

/home/miguel/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (2,24,29,205,221) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,NROFAVE,CODCLI,CODART,CODPP,CODOPE,CANVEN,CANOPE,CANOPESE,CANOPESEA,COSTOOPE,...,STATUSBT,STATUSDT,OBSTT,CHECKTT,FECHA,HORA,USUARIO,EQUIPO,MAC,IDFAVE
0,PE00000001,057,20610501010,CANOA CONFORT AL CORTE,EMPLANTILLADO,12.0,12.0,0.0,0.0,400.0,...,1,1,Fecha:29/01/2016\nHora:16:46:00\nUsuario:\nNom...,0,2016-01-25,11:04:00,NaN,Lenovo-PC,"00-FF-BF-C2-8E-52, AC-D1-B8-66-58-6B, AC-D1-B8...",162
1,PE00000001,057,20610501010,CANOA CONFORT AL CORTE,MONTADOR,12.0,12.0,0.0,0.0,1400.0,...,1,1,NaN,0,2016-01-25,11:04:00,NaN,Lenovo-PC,"00-FF-BF-C2-8E-52, AC-D1-B8-66-58-6B, AC-D1-B8...",162
2,PE00000001,057,20610501010,CANOA CONFORT AL CORTE,COSTURA,12.0,12.0,0.0,0.0,450.0,...,1,1,Fecha:29/01/2016\nHora:18:29:31\nUsuario:\nNom...,0,2016-01-25,11:04:00,NaN,Lenovo-PC,"00-FF-BF-C2-8E-52, AC-D1-B8-66-58-6B, AC-D1-B8...",162
3,PE00000001,057,20610501010,CANOA CONFORT AL CORTE,ARMADO,12.0,12.0,0.0,0.0,1200.0,...,1,1,NaN,0,2016-01-25,11:04:00,NaN,Lenovo-PC,"00-FF-BF-C2-8E-52, AC-D1-B8-66-58-6B, AC-D1-B8...",162
4,PE00000001,057,20610501010,CANOA CONFORT AL CORTE,CORTADO,12.0,12.0,0.0,0.0,200.0,...,1,1,NaN,0,2016-01-25,11:04:00,NaN,Lenovo-PC,"00-FF-BF-C2-8E-52, AC-D1-B8-66-58-6B, AC-D1-B8...",162

In [9]:
df.ix[:,20:40]

,HORATICK,CODPER,FECHAITT,HORAITT,USUARIOITT,EQUIPOITT,MACITT,FECHAFTT,HORAFTT,USUARIOFTT,EQUIPOFTT,MACFTT,CODOPEPTT,FECHAPTT,HORAPTT,STATUSN,NRONOMI,FECHAIOPE,HORAIOPE,FECHAFOPE
0,11:04:13,G-02,2008-01-01,NaN,NaN,NaN,NaN,2016-01-29,16:48:41,NaN,Servidor-PC,NaN,NaN,2008-01-01,NaN,2,21,2016-01-28,17:40:16,2016-01-29
1,11:04:13,012,2008-01-01,NaN,NaN,NaN,NaN,2016-01-29,13:41:54,NaN,Servidor-PC,NaN,NaN,2008-01-01,NaN,2,11,2016-01-28,17:40:16,2016-01-29
2,11:04:13,005,2008-01-01,NaN,NaN,NaN,NaN,2016-01-29,18:29:57,NaN,Servidor-PC,NaN,NaN,2008-01-01,NaN,2,9,2016-01-28,17:40:16,2016-01-29
3,11:04:13,002,2016-01-29,18:46:26,NaN,Servidor-PC,NaN,2016-01-29,18:47:44,NaN,Servidor-PC,NaN,NaN,2008-01-01,NaN,2,5,2016-01-28,17:40:16,2016-01-29
4,11:04:13,003,2016-01-29,17:18:21,NaN,Servidor-PC,NaN,2016-01-30,12:33:02,NaN,Servidor-PC,NaN,CORTADO,2016-01-30,12:33:02,2,15,2016-01-28,17:40:16,2016-01-29
5,11:04:13,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2016-01-28,17:40:16,2016-01-29
6,11:04:13,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2016-01-28,17:40:16,2016-01-29
7,11:04:13,13717511,2008-01-01,NaN,NaN,NaN,NaN,2016-01-28,17:40:16,2015,Servidor-PC,NaN,NaN,2008-01-01,NaN,2,4,2016-01-28,17:40:16,2016-01-29
8,11:04:13,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2016-01-28,17:40:16,2016-01-29
9,11:04:16,G-02,2008-01-01,NaN,NaN,NaN,NaN,2016-01-29,16:49:17,NaN,Servidor-PC,NaN,NaN,2008-01-01,NaN,2,21,2016-01-28,17:40:11,2016-01-29
10,11:04:16,34,2008-01-01,NaN,NaN,NaN,NaN,2016-01-29,14:00:02,NaN,Servidor-PC,NaN,NaN,2008-01-01,NaN,2,8,2016-01-28,17:40:11,2016-01-29
11,11:04:16,005,2008-01-01,NaN,NaN,NaN,NaN,2016-01-29,18:29:43,NaN,Servidor-PC,NaN,NaN,2008-01-01,NaN,2,9,2016-01-28,17:40:11,2016-01-29
12,11:04:16,002,2016-01-29,18:46:31,NaN,Servidor-PC,NaN,2016-01-29,18:47:40,NaN,Servidor-PC,NaN,NaN,2008-01-01,NaN,2,5,2016-01-28,17:40:11,2016-01-29
13,11:04:16,003,2016-01-29,17:18:24,NaN,Servidor-PC,NaN,2016-01-30,12:33:04,NaN,Servidor-PC,NaN,CORTADO,2016-01-30,12:33:04,2,15,2016-01-28,17:40:11,2016-01-29
14,11:04:16,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2016-01-28,17:40:11,2016-01-29
15,11:04:16,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2016-01-28,17:40:11,2016-01-29
16,11:04:16,13717511,2008-01-01,NaN,NaN,NaN,NaN,2016-01-28,17:40:11,2015,Servidor-PC,NaN,NaN,2008-01-01,NaN,2,4,2016-01-28,17:40:11,2016-01-29
17,11:04:16,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2016-01-28,17:40:11,2016-01-29
18,11:04:17,G-02,2008-01-01,NaN,NaN,NaN,NaN,2016-01-29,16:46:58,NaN,Servidor-PC,NaN,NaN,2008-01-01,NaN,2,21,2016-01-28,17:41:23,2016-01-29
19,11:04:17,012,2008-01-01,NaN,NaN,NaN,NaN,2016-01-29,13:42:07,NaN,Servidor-PC,NaN,NaN,2008-01-01,NaN,2,11,2016-01-28,17:41:23,2016-01-29
20,11:04:17,005,2008-01-01,NaN,NaN,NaN,NaN,2016-01-29,18:28:46,NaN,Servidor-PC,NaN,NaN,2008-01-01,NaN,2,9,2016-01-28,17:41:23,2016-01-29
21,11:04:17,014,2016-01-30,11:37:08,NaN,Servidor-PC,NaN,2016-01-30,12:49:22,NaN,Servidor-PC,NaN,ARMADO,2016-01-30,12:49:22,2,18,2016-01-28,17:41:23,2016-01-29
22,11:04:17,003,2016-01-29,17:19:03,NaN,Servidor-PC,NaN,2016-01-30,12:33:23,NaN,Servidor-PC,NaN,NaN,2008-01-01,NaN,2,15,2016-01-28,17:41:23,2016-01-29
23,11:04:17,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2016-01-28,17:41:23,2016-01-29
24,11:04:17,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2016-01-28,17:41:23,2016-01-29
25,11:04:17,13717511,2008-01-01,NaN,NaN,NaN,NaN,2016-01-28,17:41:23,2015,Servidor-PC,NaN,NaN,2008-01-01,NaN,2,4,2016-01-28,17:41:23,2016-01-29
26,11:04:17,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2016-01-28,17:41:23,2016-01-29
27,11:05:12,G-02,2008-01-01,NaN,NaN,NaN,NaN,2016-01-29,16:47:55,NaN,Servidor-PC,NaN,NaN,2008-01-01,NaN,2,21,2016-01-28,17:38:49,2016-01-29
28,11:05:12,010,2008-01-01,NaN,NaN,NaN,NaN,2016-01-30,10:50:37,NaN,Servidor-PC,NaN,NaN,2008-01-01,NaN,2,12,2016-01-28,17:38:49,2016-01-29
29,11:05:12,005,2008-01-01,NaN,NaN,NaN,NaN,2016-01-29,18:29:46,NaN,Servidor-PC,NaN,NaN,2008-01-01,NaN,2,9,2016-01-28,17:38:49,2016-01-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113798,15:10:20,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2008-01-01,NaN,2008-01-01
113799,15:10:20,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2008-01-01,NaN,2008-01-01
113800,15:10:20,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2008-01-01,NaN,2008-01-01
113801,15:10:20,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2008-01-01,NaN,2008-01-01
113802,15:10:20,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2008-01-01,NaN,2008-01-01
113803,15:10:20,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2008-01-01,NaN,2008-01-01
113804,15:10:19,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2008-01-01,NaN,2008-01-01
113805,15:10:19,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2008-01-01,NaN,2008-01-01
113806,15:10:19,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2008-01-01,NaN,2008-01-01
113807,15:10:19,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2008-01-01,NaN,2008-01-01
113808,15:10:19,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2008-01-01,NaN,2008-01-01
113809,15:10:19,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2008-01-01,NaN,2008-01-01
113810,15:10:19,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2008-01-01,NaN,2008-01-01
113811,15:10:19,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2008-01-01,NaN,2008-01-01
113812,15:10:19,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2008-01-01,NaN,2008-01-01
113813,15:10:19,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2008-01-01,NaN,2008-01-01
113814,15:10:19,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2008-01-01,NaN,2008-01-01
113815,15:10:19,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2008-01-01,NaN,2008-01-01
113816,15:10:19,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2008-01-01,NaN,2008-01-01
113817,15:10:19,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2008-01-01,NaN,2008-01-01
113818,15:10:19,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2008-01-01,NaN,2008-01-01
113819,15:10:19,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2008-01-01,NaN,2008-01-01
113820,15:10:19,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2008-01-01,NaN,2008-01-01
113821,15:10:19,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2008-01-01,NaN,2008-01-01
113822,15:10:19,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2008-01-01,NaN,2008-01-01
113823,15:10:19,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2008-01-01,NaN,2008-01-01
113824,15:10:19,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2008-01-01,NaN,2008-01-01
113825,15:10:19,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2008-01-01,NaN,2008-01-01
113826,15:10:19,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2008-01-01,NaN,2008-01-01
113827,15:10:19,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN,NaN,NaN,NaN,2008-01-01,NaN,1,0,2008-01-01,NaN,2008-01-01

In [31]:
df[[column for column in df.columns if 'HORA'| 'FECHA' in column]]

        HORATICK   HORAITT   HORAFTT   HORAPTT  HORAIOPE  HORAFOPE      HORA
0       11:04:13       NaN  16:48:41       NaN  17:40:16  16:48:41  11:04:00
1       11:04:13       NaN  13:41:54       NaN  17:40:16  16:48:41  11:04:00
2       11:04:13       NaN  18:29:57       NaN  17:40:16  16:48:41  11:04:00
3       11:04:13  18:46:26  18:47:44       NaN  17:40:16  16:48:41  11:04:00
4       11:04:13  17:18:21  12:33:02  12:33:02  17:40:16  16:48:41  11:04:00
5       11:04:13       NaN       NaN       NaN  17:40:16  16:48:41  11:04:00
6       11:04:13       NaN       NaN       NaN  17:40:16  16:48:41  11:04:00
7       11:04:13       NaN  17:40:16       NaN  17:40:16  16:48:41  11:04:00
8       11:04:13       NaN       NaN       NaN  17:40:16  16:48:41  11:04:00
9       11:04:16       NaN  16:49:17       NaN  17:40:11  16:49:17  11:04:00
10      11:04:16       NaN  14:00:02       NaN  17:40:11  16:49:17  11:04:00
11      11:04:16       NaN  18:29:43       NaN  17:40:11  16:49:17  11:04:00
12      11:04:16  18:46:31  18:47:40       NaN  17:40:11  16:49:17  11:04:00
13      11:04:16  17:18:24  12:33:04  12:33:04  17:40:11  16:49:17  11:04:00
14      11:04:16       NaN       NaN       NaN  17:40:11  16:49:17  11:04:00
15      11:04:16       NaN       NaN       NaN  17:40:11  16:49:17  11:04:00
16      11:04:16       NaN  17:40:11       NaN  17:40:11  16:49:17  11:04:00
17      11:04:16       NaN       NaN       NaN  17:40:11  16:49:17  11:04:00
18      11:04:17       NaN  16:46:58       NaN  17:41:23  16:46:58  11:04:00
19      11:04:17       NaN  13:42:07       NaN  17:41:23  16:46:58  11:04:00
20      11:04:17       NaN  18:28:46       NaN  17:41:23  16:46:58  11:04:00
21      11:04:17  11:37:08  12:49:22  12:49:22  17:41:23  16:46:58  11:04:00
22      11:04:17  17:19:03  12:33:23       NaN  17:41:23  16:46:58  11:04:00
23      11:04:17       NaN       NaN       NaN  17:41:23  16:46:58  11:04:00
24      11:04:17       NaN       NaN       NaN  17:41:23  16:46:58  11:04:00
25      11:04:17       NaN  17:41:23       NaN  17:41:23  16:46:58  11:04:00
26      11:04:17       NaN       NaN       NaN  17:41:23  16:46:58  11:04:00
27      11:05:12       NaN  16:47:55       NaN  17:38:49  16:47:55  11:04:32
28      11:05:12       NaN  10:50:37       NaN  17:38:49  16:47:55  11:04:32
29      11:05:12       NaN  18:29:46       NaN  17:38:49  16:47:55  11:04:32
...          ...       ...       ...       ...       ...       ...       ...
113798  15:10:20       NaN       NaN       NaN       NaN       NaN  15:10:10
113799  15:10:20       NaN       NaN       NaN       NaN       NaN  15:10:10
113800  15:10:20       NaN       NaN       NaN       NaN       NaN  15:10:10
113801  15:10:20       NaN       NaN       NaN       NaN       NaN  15:10:10
113802  15:10:20       NaN       NaN       NaN       NaN       NaN  15:10:10
113803  15:10:20       NaN       NaN       NaN       NaN       NaN  15:10:10
113804  15:10:19       NaN       NaN       NaN       NaN       NaN  15:10:10
113805  15:10:19       NaN       NaN       NaN       NaN       NaN  15:10:10
113806  15:10:19       NaN       NaN       NaN       NaN       NaN  15:10:10
113807  15:10:19       NaN       NaN       NaN       NaN       NaN  15:10:11
113808  15:10:19       NaN       NaN       NaN       NaN       NaN  15:10:11
113809  15:10:19       NaN       NaN       NaN       NaN       NaN  15:10:11
113810  15:10:19       NaN       NaN       NaN       NaN       NaN  15:10:11
113811  15:10:19       NaN       NaN       NaN       NaN       NaN  15:10:11
113812  15:10:19       NaN       NaN       NaN       NaN       NaN  15:10:11
113813  15:10:19       NaN       NaN       NaN       NaN       NaN  15:10:11
113814  15:10:19       NaN       NaN       NaN       NaN       NaN  15:10:11
113815  15:10:19       NaN       NaN       NaN       NaN       NaN  15:10:11
113816  15:10:19       NaN       NaN       NaN       NaN       NaN  15:10:12
113817  15:10:19       NaN       NaN       NaN       NaN       NaN  15:10:12
113818  15:10:19       NaN       NaN       NaN       NaN       NaN  15:10:12
113819  15:10:19       NaN       NaN       NaN       NaN       NaN  15:10:12
113820  15:10:19       NaN       NaN       NaN       NaN       NaN  15:10:12
113821  15:10:19       NaN       NaN       NaN       NaN       NaN  15:10:12
113822  15:10:19       NaN       NaN       NaN       NaN       NaN  15:10:12
113823  15:10:19       NaN       NaN       NaN       NaN       NaN  15:10:12
113824  15:10:19       NaN       NaN       NaN       NaN       NaN  15:10:13
113825  15:10:19       NaN       NaN       NaN       NaN       NaN  15:10:13
113826  15:10:19       NaN       NaN       NaN       NaN       NaN  15:10:13
113827  15:10:19       NaN       NaN       NaN       NaN       NaN  15:10:13

[113828 rows x 7 columns]