In [159]:
## Getting data
!wget -O source.zip https://www.dropbox.com/s/dy8xyabnahh8onk/source.zip?dl=0
!unzip source.zip -d source

--2017-12-05 19:58:26--  https://www.dropbox.com/s/dy8xyabnahh8onk/source.zip?dl=0
Resolviendo www.dropbox.com (www.dropbox.com)... 162.125.5.1, 2620:100:601d:1::a27d:501
Conectando con www.dropbox.com (www.dropbox.com)[162.125.5.1]:443... conectado.
Petición HTTP enviada, esperando respuesta... 302 Found
Ubicación: https://dl.dropboxusercontent.com/content_link/tLPgAWrqNMmrlAqD6Szpy30TMwZ1WcFHFFICooHwX2RbBAIDqzihhYeniF1hBzcC/file [siguiente]
--2017-12-05 19:58:27--  https://dl.dropboxusercontent.com/content_link/tLPgAWrqNMmrlAqD6Szpy30TMwZ1WcFHFFICooHwX2RbBAIDqzihhYeniF1hBzcC/file
Resolviendo dl.dropboxusercontent.com (dl.dropboxusercontent.com)... 162.125.5.6, 2620:100:601d:6::a27d:506
Conectando con dl.dropboxusercontent.com (dl.dropboxusercontent.com)[162.125.5.6]:443... conectado.
Petición HTTP enviada, esperando respuesta... 200 OK
Longitud: 12141343 (12M) [application/zip]
Grabando a: “source.zip”

source.zip           60%[===========>        ]   6,99M   410KB/s    eta 11s    ^C
Archive:  source.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of source.zip or
        source.zip.zip, and cannot find source.zip.ZIP, period.

In [250]:
import pandas as pd
import plotly.plotly as py
import plotly.graph_objs as go
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('source/tareasytickets.csv')
original = pd.read_csv('source/tareasytickets.csv')
df.head()

,NROFAVE,CODCLI,CODART,CODPP,CODOPE,CANVEN,CANOPE,CANOPESE,CANOPESEA,COSTOOPE,...,STATUSBT,STATUSDT,OBSTT,CHECKTT,FECHA,HORA,USUARIO,EQUIPO,MAC,IDFAVE
0,PE00000001,057,20610501010,CANOA CONFORT AL CORTE,EMPLANTILLADO,12.0,12.0,0.0,0.0,400.0,...,1,1,Fecha:29/01/2016\nHora:16:46:00\nUsuario:\nNom...,0,2016-01-25,11:04:00,NaN,Lenovo-PC,"00-FF-BF-C2-8E-52, AC-D1-B8-66-58-6B, AC-D1-B8...",162
1,PE00000001,057,20610501010,CANOA CONFORT AL CORTE,MONTADOR,12.0,12.0,0.0,0.0,1400.0,...,1,1,NaN,0,2016-01-25,11:04:00,NaN,Lenovo-PC,"00-FF-BF-C2-8E-52, AC-D1-B8-66-58-6B, AC-D1-B8...",162
2,PE00000001,057,20610501010,CANOA CONFORT AL CORTE,COSTURA,12.0,12.0,0.0,0.0,450.0,...,1,1,Fecha:29/01/2016\nHora:18:29:31\nUsuario:\nNom...,0,2016-01-25,11:04:00,NaN,Lenovo-PC,"00-FF-BF-C2-8E-52, AC-D1-B8-66-58-6B, AC-D1-B8...",162
3,PE00000001,057,20610501010,CANOA CONFORT AL CORTE,ARMADO,12.0,12.0,0.0,0.0,1200.0,...,1,1,NaN,0,2016-01-25,11:04:00,NaN,Lenovo-PC,"00-FF-BF-C2-8E-52, AC-D1-B8-66-58-6B, AC-D1-B8...",162
4,PE00000001,057,20610501010,CANOA CONFORT AL CORTE,CORTADO,12.0,12.0,0.0,0.0,200.0,...,1,1,NaN,0,2016-01-25,11:04:00,NaN,Lenovo-PC,"00-FF-BF-C2-8E-52, AC-D1-B8-66-58-6B, AC-D1-B8...",162

Agrupamos por Código de Operador buscando analizar la cantidad de transacciones por operador

In [251]:
df.groupby('CODOPE').count()

,NROFAVE,CODCLI,CODART,CODPP,CANVEN,CANOPE,CANOPESE,CANOPESEA,COSTOOPE,COSTOOPEC,...,STATUSBT,STATUSDT,OBSTT,CHECKTT,FECHA,HORA,USUARIO,EQUIPO,MAC,IDFAVE
CODOPE,,,,,,,,,,,,,,,,,,,,,
ARMADO,15263,15263,15913,15913,15913,15913,15913,15913,15913,15913,...,15913,15913,744,15913,15913,15913,452,15913,15913,15913
BORDADO,2325,2325,2327,2327,2327,2327,2327,2327,2327,2327,...,2327,2327,2,2327,2327,2327,45,2327,2327,2327
CONTROL PLANTA,294,294,294,294,294,294,294,294,294,294,...,294,294,0,294,294,294,0,294,294,294
CORTADO,15148,15148,15583,15583,15583,15583,15583,15583,15583,15583,...,15583,15583,785,15583,15583,15583,362,15583,15583,15583
COSTURA,15260,15260,15322,15322,15322,15322,15322,15322,15322,15322,...,15322,15322,66,15322,15322,15322,251,15322,15322,15322
DECORADO,709,709,709,709,709,709,709,709,709,709,...,709,709,0,709,709,709,56,709,709,709
EMPLANTILLADO,15210,15210,15562,15562,15562,15562,15562,15562,15562,15562,...,15562,15562,242,15562,15562,15562,343,15562,15562,15562
ESTAMPADO,677,677,677,677,677,677,677,677,677,677,...,677,677,0,677,677,677,0,677,677,677
FORRADO DE PLANTA,7818,7818,7838,7838,7838,7838,7838,7838,7838,7838,...,7838,7838,21,7838,7838,7838,30,7838,7838,7838
FORRADO DE PLANTILLAS,40,40,40,40,40,40,40,40,40,40,...,40,40,0,40,40,40,0,40,40,40
FORRADO DE TACONES,149,149,149,149,149,149,149,149,149,149,...,149,149,0,149,149,149,0,149,149,149
LASER,4288,4288,4288,4288,4288,4288,4288,4288,4288,4288,...,4288,4288,0,4288,4288,4288,140,4288,4288,4288
MONTADOR,15269,15269,15569,15569,15569,15569,15569,15569,15569,15569,...,15569,15569,384,15569,15569,15569,329,15569,15569,15569
PLANTILLAS,12387,12387,12419,12419,12419,12419,12419,12419,12419,12419,...,12419,12419,32,12419,12419,12419,243,12419,12419,12419
SELLOS,284,284,284,284,284,284,284,284,284,284,...,284,284,0,284,284,284,0,284,284,284
SUELAS,6839,6839,6854,6854,6854,6854,6854,6854,6854,6854,...,6854,6854,15,6854,6854,6854,218,6854,6854,6854

## Análisis de Columnas

In [252]:
# Profundidad de las filas
a,b = 0,10

# Decodificacion de Columnas
CODCLI = 'Codigo de Cliente'
CODART = 'Codigo de Articulo'
CODPP  = 'Codigo Procesos de Produccion'
CODOPE = 'Codigo de Procesos'
CANVEN = 'Cantidad Pedido'
CANOPESE = 'Cantidad Operaciones Sin Elaborar'
CANOPE = 'Cantidad Operaciones'
CANOPESEA = 'Cantidad Operaciones sin Elaborar Alta'
COSTOOPE = 'Costo Operacion Cuando se Crea'
COSTOOPEC = 'Costo Operacion'
TICKET = 'Codigo de Barras Ticket'
NROORDP = 'Numero de Pedido'
NROINV = 'Numero de Plantilla o Lote'
FECINV = 'Fecha Plantilla'
NROPLA = 'Numero de Planificacion'
FECPLA = 'Fecha Planificacion'
FECHATICK = 'Fecha cuando se guarda el Ticket'
HORATICK = 'Hora cuando se guarda el Ticket'
CODPER = 'Codigo Personal'
FECHAITT = 'Fecha Inicio Tarea'
HORAFTT = 'Hora Fin Tarea'
CODOPEPTT = 'Codigo de Operacion Parada'
FECHAPTT = 'Fecha Tarea Parada'
HORAPTT = 'Hora Tarea Parada'
STATUSN = 'Estado Nomina'
FECHAIOPE = 'Fecha Inicio Operacion'
HORAIOPE = 'Horario Inicio Operacion'
FECHAFOPE = 'Fecha Fin Operacion'
HORAFOPE = 'Hora Fin Operacion'
NROFACT = 'Numero Factura'
FECFACT = 'Fecha Factura'
STATUSF = 'Estado si es 0 se facturo todo'
CANTICKIMP = 'Cantidad Tickets Impresos'
FECTICKIMP = 'Fecha cuando se imprime el Ticket'
DESNMAT1 = 'Nota Material 1'
FECHA = 'Fecha'
HORA = 'Hora'
IDFAVE = 'Id del Articulo Detalle de Ventas'

leyendas = [CODCLI ,CODART ,CODPP  ,CODOPE ,CANVEN ,CANOPESE ,CANOPE ,CANOPESEA ,COSTOOPE ,COSTOOPEC ,TICKET ,NROORDP ,NROINV ,FECINV ,NROPLA ,FECPLA ,FECHATICK ,HORATICK ,CODPER ,FECHAITT ,HORAFTT ,CODOPEPTT ,FECHAPTT ,HORAPTT ,STATUSN ,FECHAIOPE ,HORAIOPE ,FECHAFOPE ,HORAFOPE ,NROFACT ,FECFACT ,STATUSF ,CANTICKIMP ,FECTICKIMP ,DESNMAT1 ,FECHA ,HORA ,IDFAVE]
leyendas_index = ['CODCLI' ,'CODART','CODPP','CODOPE','CANVEN','CANOPESE','CANOPE','CANOPESEA','COSTOOPE','COSTOOPEC','TICKET','NROORDP','NROINV','FECINV','NROPLA','FECPLA','FECHATICK','HORATICK','CODPER','FECHAITT','HORAFTT','CODOPEPTT','FECHAPTT','HORAPTT','STATUSN','FECHAIOPE','HORAIOPE','FECHAFOPE','HORAFOPE','NROFACT','FECFACT','STATUSF','CANTICKIMP','FECTICKIMP','DESNMAT1','FECHA','HORA','IDFAVE']
leyendas_df = pd.DataFrame(leyendas, index=leyendas_index , columns=['Leyenda'])

In [253]:
df.iloc[a:b,:10]

,NROFAVE,CODCLI,CODART,CODPP,CODOPE,CANVEN,CANOPE,CANOPESE,CANOPESEA,COSTOOPE
0,PE00000001,057,20610501010,CANOA CONFORT AL CORTE,EMPLANTILLADO,12.0,12.0,0.0,0.0,400.0
1,PE00000001,057,20610501010,CANOA CONFORT AL CORTE,MONTADOR,12.0,12.0,0.0,0.0,1400.0
2,PE00000001,057,20610501010,CANOA CONFORT AL CORTE,COSTURA,12.0,12.0,0.0,0.0,450.0
3,PE00000001,057,20610501010,CANOA CONFORT AL CORTE,ARMADO,12.0,12.0,0.0,0.0,1200.0
4,PE00000001,057,20610501010,CANOA CONFORT AL CORTE,CORTADO,12.0,12.0,0.0,0.0,200.0
5,PE00000001,057,20610501010,CANOA CONFORT AL CORTE,ESTAMPADO,12.0,12.0,0.0,0.0,200.0
6,PE00000001,057,20610501010,CANOA CONFORT AL CORTE,SELLOS,12.0,12.0,0.0,0.0,0.0
7,PE00000001,057,20610501010,CANOA CONFORT AL CORTE,FORRADO DE PLANTA,12.0,12.0,0.0,0.0,500.0
8,PE00000001,057,20610501010,CANOA CONFORT AL CORTE,PLANTILLAS,12.0,12.0,0.0,0.0,0.0
9,PE00000001,057,20614801010,CANOA CONFORT AL CORTE,EMPLANTILLADO,12.0,12.0,0.0,0.0,400.0

**Columnas Relevantes: **
CODCLI, CODPP, CODOPE, CANVEN, CANOPE, COSTOOPE

In [254]:
df.iloc[a:b,10:20]

,COSTOOPEC,TICKET,NROORDP,NROINV,FECINV,NROPLA,FECPLA,NROTICK,NROTICKC,FECHATICK
0,400.0,10003201001,0,0,2008-01-01,0,2008-01-01,1,1,2016-01-25
1,1400.0,10003202001,0,0,2008-01-01,0,2008-01-01,1,1,2016-01-25
2,450.0,10003203001,0,0,2008-01-01,0,2008-01-01,1,1,2016-01-25
3,1200.0,10003204001,0,0,2008-01-01,0,2008-01-01,1,1,2016-01-25
4,200.0,10003205001,0,0,2008-01-01,0,2008-01-01,1,1,2016-01-25
5,200.0,10003206001,0,0,2008-01-01,0,2008-01-01,1,1,2016-01-25
6,0.0,10003207001,0,0,2008-01-01,0,2008-01-01,1,1,2016-01-25
7,500.0,10003208001,0,0,2008-01-01,0,2008-01-01,1,1,2016-01-25
8,0.0,10003209001,0,0,2008-01-01,0,2008-01-01,1,1,2016-01-25
9,400.0,10003201002,0,0,2008-01-01,0,2008-01-01,2,2,2016-01-25

**Columnas Relevantes: **
COSTOOPEC, TICKET, NROTICK, FECHATICK

+ ¿Qué diferencia hay entre TICKET y NROTICKC?
+ ¿Porqué FECINV, FECPLA es diferente de FECHATICK?

In [255]:
df.iloc[a:b,20:30]

,HORATICK,CODPER,FECHAITT,HORAITT,USUARIOITT,EQUIPOITT,MACITT,FECHAFTT,HORAFTT,USUARIOFTT
0,11:04:13,G-02,2008-01-01,NaN,NaN,NaN,NaN,2016-01-29,16:48:41,NaN
1,11:04:13,012,2008-01-01,NaN,NaN,NaN,NaN,2016-01-29,13:41:54,NaN
2,11:04:13,005,2008-01-01,NaN,NaN,NaN,NaN,2016-01-29,18:29:57,NaN
3,11:04:13,002,2016-01-29,18:46:26,NaN,Servidor-PC,NaN,2016-01-29,18:47:44,NaN
4,11:04:13,003,2016-01-29,17:18:21,NaN,Servidor-PC,NaN,2016-01-30,12:33:02,NaN
5,11:04:13,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN
6,11:04:13,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN
7,11:04:13,13717511,2008-01-01,NaN,NaN,NaN,NaN,2016-01-28,17:40:16,2015
8,11:04:13,NaN,2008-01-01,NaN,NaN,NaN,NaN,2008-01-01,NaN,NaN
9,11:04:16,G-02,2008-01-01,NaN,NaN,NaN,NaN,2016-01-29,16:49:17,NaN

**Columnas Relevantes: **
HORATICK, FECHAITT, HORAITT, FECHAFTT, HORAFTT

+ ¿Qué es CODPER, ITT?
+ ¿Porqué el salto tan abrupto en FECHAFTT?

In [256]:
df.iloc[a:b,30:40]

,EQUIPOFTT,MACFTT,CODOPEPTT,FECHAPTT,HORAPTT,STATUSN,NRONOMI,FECHAIOPE,HORAIOPE,FECHAFOPE
0,Servidor-PC,NaN,NaN,2008-01-01,NaN,2,21,2016-01-28,17:40:16,2016-01-29
1,Servidor-PC,NaN,NaN,2008-01-01,NaN,2,11,2016-01-28,17:40:16,2016-01-29
2,Servidor-PC,NaN,NaN,2008-01-01,NaN,2,9,2016-01-28,17:40:16,2016-01-29
3,Servidor-PC,NaN,NaN,2008-01-01,NaN,2,5,2016-01-28,17:40:16,2016-01-29
4,Servidor-PC,NaN,CORTADO,2016-01-30,12:33:02,2,15,2016-01-28,17:40:16,2016-01-29
5,NaN,NaN,NaN,2008-01-01,NaN,1,0,2016-01-28,17:40:16,2016-01-29
6,NaN,NaN,NaN,2008-01-01,NaN,1,0,2016-01-28,17:40:16,2016-01-29
7,Servidor-PC,NaN,NaN,2008-01-01,NaN,2,4,2016-01-28,17:40:16,2016-01-29
8,NaN,NaN,NaN,2008-01-01,NaN,1,0,2016-01-28,17:40:16,2016-01-29
9,Servidor-PC,NaN,NaN,2008-01-01,NaN,2,21,2016-01-28,17:40:11,2016-01-29

**Columnas Relevantes: **
FECHAIOPE, HORAIOPE, FECHAFOPE

+ ¿Qué es PTT?
+ ¿Porqué sólo hay un registro en HORAPTT?

In [257]:
df.iloc[a:b,40:50]

,HORAFOPE,NROFACT,FECFACT,STATUSF,CANTICKIMP,FECTICKIMP,FECRTICKIMP,IDPROTICKETS,TALLA00,TALLA01
0,16:48:41,NaN,2008-01-01,1,1,2016-01-25,2008-01-01,1,0,0
1,16:48:41,NaN,2008-01-01,1,1,2016-01-25,2008-01-01,2,0,0
2,16:48:41,NaN,2008-01-01,1,1,2016-01-25,2008-01-01,3,0,0
3,16:48:41,NaN,2008-01-01,1,1,2016-01-25,2008-01-01,4,0,0
4,16:48:41,NaN,2008-01-01,1,1,2016-01-25,2008-01-01,5,0,0
5,16:48:41,NaN,2008-01-01,1,1,2016-01-25,2008-01-01,6,0,0
6,16:48:41,NaN,2008-01-01,1,1,2016-01-25,2008-01-01,7,0,0
7,16:48:41,NaN,2008-01-01,1,1,2016-01-25,2008-01-01,8,0,0
8,16:48:41,NaN,2008-01-01,1,1,2016-01-25,2008-01-01,9,0,0
9,16:49:17,NaN,2008-01-01,1,1,2016-01-25,2008-01-01,10,0,0

**Columnas Relevantes: **
HORAFOPE, IDPROTICKETS

+ ¿Porqué FECFACT, FECRTICKIMP tiene un registro tan antiguo?
+ ¿Porqué FECINV, FECPLA es diferente de FECHATICK?

In [258]:
df.iloc[a:b,50:60]

,TALLA02,TALLA03,TALLA04,TALLA05,TALLA06,TALLA07,TALLA08,TALLA09,TALLA10,TALLA11
0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0

In [259]:
df.iloc[a:b,60:70]

,TALLA12,TALLA13,TALLA14,TALLA15,TALLA16,TALLA17,TALLA18,TALLA19,TALLA20,TALLA21
0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0

In [260]:
df.iloc[a:b,70:80]

,TALLA22,TALLA23,TALLA24,TALLA25,TALLA26,TALLA27,TALLA28,TALLA29,TALLA30,TALLA31
0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0

In [261]:
df.iloc[a:b,90:100]

,TALLA42,TALLA43,TALLA44,TALLA45,TALLA46,TALLA47,TALLA48,TALLA49,TALLA50,TALLA51
0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0

In [262]:
df.iloc[a:b,100:110]

,TALLA52,TALLA53,TALLA54,TALLA55,TALLA56,CODART1,CANART1,CODART2,CANART2,CODART3
0,0,0,0,0,0,NaN,0.0,NaN,0.0,NaN
1,0,0,0,0,0,NaN,0.0,NaN,0.0,NaN
2,0,0,0,0,0,NaN,0.0,NaN,0.0,NaN
3,0,0,0,0,0,NaN,0.0,NaN,0.0,NaN
4,0,0,0,0,0,NaN,0.0,NaN,0.0,NaN
5,0,0,0,0,0,NaN,0.0,NaN,0.0,NaN
6,0,0,0,0,0,NaN,0.0,NaN,0.0,NaN
7,0,0,0,0,0,NaN,0.0,NaN,0.0,NaN
8,0,0,0,0,0,NaN,0.0,NaN,0.0,NaN
9,0,0,0,0,0,NaN,0.0,NaN,0.0,NaN

In [263]:
df.iloc[a:b,110:120]

,CANART3,CODART4,CANART4,CODART5,CANART5,CODART6,CANART6,CODART7,CANART7,CODART8
0,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
1,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
2,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
3,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
4,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
5,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
6,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
7,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
8,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
9,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN

In [264]:
df.iloc[a:b,120:130]

,CANART8,CODART9,CANART9,CODART10,CANART10,CODART11,CANART11,CODART12,CANART12,CODART13
0,0.0,NaN,0.0,NaN,0.0,16.0,2.0,NaN,0.0,NaN
1,0.0,NaN,0.0,NaN,0.0,16.0,2.0,NaN,0.0,NaN
2,0.0,NaN,0.0,NaN,0.0,16.0,2.0,NaN,0.0,NaN
3,0.0,NaN,0.0,NaN,0.0,16.0,2.0,NaN,0.0,NaN
4,0.0,NaN,0.0,NaN,0.0,16.0,2.0,NaN,0.0,NaN
5,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
6,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
7,0.0,NaN,0.0,NaN,0.0,16.0,2.0,NaN,0.0,NaN
8,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
9,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN

In [265]:
df.iloc[a:b,130:140]

,CANART13,CODART14,CANART14,CODART15,CANART15,CODART16,CANART16,CODART17,CANART17,CODART18
0,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
1,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
2,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
3,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
4,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
5,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
6,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
7,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
8,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
9,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN

In [266]:
df.iloc[a:b,140:150]

,CANART18,CODART19,CANART19,CODART20,CANART20,TALLAISB1,TALLAISB2,TALLAISB3,TALLAISB4,TALLAISB5
0,0.0,NaN,0.0,NaN,0.0,1,1,1,1,1
1,0.0,NaN,0.0,NaN,0.0,1,1,1,1,1
2,0.0,NaN,0.0,NaN,0.0,1,1,1,1,1
3,0.0,NaN,0.0,NaN,0.0,1,1,1,1,1
4,0.0,NaN,0.0,NaN,0.0,1,1,1,1,1
5,0.0,NaN,0.0,NaN,0.0,1,1,1,1,1
6,0.0,NaN,0.0,NaN,0.0,1,1,1,1,1
7,0.0,NaN,0.0,NaN,0.0,1,1,1,1,1
8,0.0,NaN,0.0,NaN,0.0,1,1,1,1,1
9,0.0,NaN,0.0,NaN,0.0,1,1,1,1,1

In [267]:
df.iloc[a:b,150:160]

,TALLAISB6,TALLAISB7,TALLAISB8,TALLAISB9,TALLAISB10,TALLAISB11,TALLAISB12,TALLAISB13,TALLAISB14,TALLAISB15
0,1,1,1,1,1,1,1,1,1,1
1,1,1,1,1,1,1,1,1,1,1
2,1,1,1,1,1,1,1,1,1,1
3,1,1,1,1,1,1,1,1,1,1
4,1,1,1,1,1,1,1,1,1,1
5,1,1,1,1,1,1,1,1,1,1
6,1,1,1,1,1,1,1,1,1,1
7,1,1,1,1,1,1,1,1,1,1
8,1,1,1,1,1,1,1,1,1,1
9,1,1,1,1,1,1,1,1,1,1

In [268]:
df.iloc[a:b,160:170]

,TALLAISB16,TALLAISB17,TALLAISB18,TALLAISB19,TALLAISB20,PARTES1,PARTES2,PARTES3,PARTES4,PARTES5
0,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN
1,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN
2,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN
3,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN
4,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN
5,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN
6,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN
7,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN
8,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN
9,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN

In [269]:
df.iloc[a:b,170:180]

,PARTES6,PARTES7,PARTES8,PARTES9,PARTES10,PARTES11,PARTES12,PARTES13,PARTES14,PARTES15
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [270]:
df.iloc[a:b,180:190]

,PARTES16,PARTES17,PARTES18,PARTES19,PARTES20,PARTESP1,PARTESP2,PARTESP3,PARTESP4,PARTESP5
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [271]:
df.iloc[a:b,190:200]

,PARTESP6,PARTESP7,PARTESP8,PARTESP9,PARTESP10,PARTESP11,PARTESP12,PARTESP13,PARTESP14,PARTESP15
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [272]:
df.iloc[a:b,200:210]

,PARTESP16,PARTESP17,PARTESP18,PARTESP19,PARTESP20,DESNMAT1,DESNMAT2,DESNMAT3,DESNMAT4,MATERIALES
0,NaN,NaN,NaN,NaN,NaN,FUCSIA FUCSIA,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,FUCSIA FUCSIA,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,FUCSIA FUCSIA,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,FUCSIA FUCSIA,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,FUCSIA FUCSIA,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,FUCSIA FUCSIA,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,FUCSIA FUCSIA,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,FUCSIA FUCSIA,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,FUCSIA FUCSIA,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,FUCSIA FUCSIA,NaN,NaN,NaN,NaN

In [273]:
df.iloc[a:b,210:220]

,DESSER,DESDA,DESOPE,STATUSPT,STATUSTA,STATUSBT,STATUSDT,OBSTT,CHECKTT,FECHA
0,NaN,NaN,NaN,1,1,1,1,Fecha:29/01/2016\nHora:16:46:00\nUsuario:\nNom...,0,2016-01-25
1,NaN,NaN,NaN,1,1,1,1,NaN,0,2016-01-25
2,NaN,NaN,NaN,1,1,1,1,Fecha:29/01/2016\nHora:18:29:31\nUsuario:\nNom...,0,2016-01-25
3,NaN,NaN,NaN,1,1,1,1,NaN,0,2016-01-25
4,NaN,NaN,NaN,1,1,1,1,NaN,0,2016-01-25
5,NaN,NaN,NaN,1,0,1,1,NaN,0,2016-01-25
6,NaN,NaN,NaN,1,0,1,1,NaN,0,2016-01-25
7,NaN,NaN,NaN,1,1,1,1,NaN,0,2016-01-25
8,NaN,NaN,NaN,1,0,1,1,NaN,0,2016-01-25
9,NaN,NaN,NaN,1,1,1,1,Fecha:29/01/2016\nHora:16:46:29\nUsuario:\nNom...,0,2016-01-25

In [274]:
df.iloc[a:b,220:225]

,HORA,USUARIO,EQUIPO,MAC,IDFAVE
0,11:04:00,NaN,Lenovo-PC,"00-FF-BF-C2-8E-52, AC-D1-B8-66-58-6B, AC-D1-B8...",162
1,11:04:00,NaN,Lenovo-PC,"00-FF-BF-C2-8E-52, AC-D1-B8-66-58-6B, AC-D1-B8...",162
2,11:04:00,NaN,Lenovo-PC,"00-FF-BF-C2-8E-52, AC-D1-B8-66-58-6B, AC-D1-B8...",162
3,11:04:00,NaN,Lenovo-PC,"00-FF-BF-C2-8E-52, AC-D1-B8-66-58-6B, AC-D1-B8...",162
4,11:04:00,NaN,Lenovo-PC,"00-FF-BF-C2-8E-52, AC-D1-B8-66-58-6B, AC-D1-B8...",162
5,11:04:00,NaN,Lenovo-PC,"00-FF-BF-C2-8E-52, AC-D1-B8-66-58-6B, AC-D1-B8...",162
6,11:04:00,NaN,Lenovo-PC,"00-FF-BF-C2-8E-52, AC-D1-B8-66-58-6B, AC-D1-B8...",162
7,11:04:00,NaN,Lenovo-PC,"00-FF-BF-C2-8E-52, AC-D1-B8-66-58-6B, AC-D1-B8...",162
8,11:04:00,NaN,Lenovo-PC,"00-FF-BF-C2-8E-52, AC-D1-B8-66-58-6B, AC-D1-B8...",162
9,11:04:00,NaN,Lenovo-PC,"00-FF-BF-C2-8E-52, AC-D1-B8-66-58-6B, AC-D1-B8...",163

**Columnas Relevantes: **
HORA

+ ¿Hay registros en USUARIO?

## Filtramos Columnas más Relevantes

In [275]:
relevantes = ['NROFAVE','CODCLI', 'CODPP', 'CODOPE', 'CANVEN', 'CANOPE', 'COSTOOPE', 'COSTOOPEC', 'TICKET', 'NROTICKC', 'FECHATICK', 'HORATICK', 'FECHAITT', 'HORAITT', 'FECHAFTT', 'HORAFTT', 'FECHAIOPE', 'HORAIOPE', 'FECHAFOPE', 'HORAFOPE', 'IDPROTICKETS', 'FECHA', 'HORA']
df = df[relevantes]
df.iloc[:10,:].head()

,NROFAVE,CODCLI,CODPP,CODOPE,CANVEN,CANOPE,COSTOOPE,COSTOOPEC,TICKET,NROTICKC,...,HORAITT,FECHAFTT,HORAFTT,FECHAIOPE,HORAIOPE,FECHAFOPE,HORAFOPE,IDPROTICKETS,FECHA,HORA
0,PE00000001,057,CANOA CONFORT AL CORTE,EMPLANTILLADO,12.0,12.0,400.0,400.0,10003201001,1,...,NaN,2016-01-29,16:48:41,2016-01-28,17:40:16,2016-01-29,16:48:41,1,2016-01-25,11:04:00
1,PE00000001,057,CANOA CONFORT AL CORTE,MONTADOR,12.0,12.0,1400.0,1400.0,10003202001,1,...,NaN,2016-01-29,13:41:54,2016-01-28,17:40:16,2016-01-29,16:48:41,2,2016-01-25,11:04:00
2,PE00000001,057,CANOA CONFORT AL CORTE,COSTURA,12.0,12.0,450.0,450.0,10003203001,1,...,NaN,2016-01-29,18:29:57,2016-01-28,17:40:16,2016-01-29,16:48:41,3,2016-01-25,11:04:00
3,PE00000001,057,CANOA CONFORT AL CORTE,ARMADO,12.0,12.0,1200.0,1200.0,10003204001,1,...,18:46:26,2016-01-29,18:47:44,2016-01-28,17:40:16,2016-01-29,16:48:41,4,2016-01-25,11:04:00
4,PE00000001,057,CANOA CONFORT AL CORTE,CORTADO,12.0,12.0,200.0,200.0,10003205001,1,...,17:18:21,2016-01-30,12:33:02,2016-01-28,17:40:16,2016-01-29,16:48:41,5,2016-01-25,11:04:00

### Buscamos Columnas que contengan Hora o Fecha

Con la esperanza de encontrar algún patrón adicional

In [276]:
original.loc[:,original.columns.str.contains("HORA|FECHA")].head()

,FECHATICK,HORATICK,FECHAITT,HORAITT,FECHAFTT,HORAFTT,FECHAPTT,HORAPTT,FECHAIOPE,HORAIOPE,FECHAFOPE,HORAFOPE,FECHA,HORA
0,2016-01-25,11:04:13,2008-01-01,NaN,2016-01-29,16:48:41,2008-01-01,NaN,2016-01-28,17:40:16,2016-01-29,16:48:41,2016-01-25,11:04:00
1,2016-01-25,11:04:13,2008-01-01,NaN,2016-01-29,13:41:54,2008-01-01,NaN,2016-01-28,17:40:16,2016-01-29,16:48:41,2016-01-25,11:04:00
2,2016-01-25,11:04:13,2008-01-01,NaN,2016-01-29,18:29:57,2008-01-01,NaN,2016-01-28,17:40:16,2016-01-29,16:48:41,2016-01-25,11:04:00
3,2016-01-25,11:04:13,2016-01-29,18:46:26,2016-01-29,18:47:44,2008-01-01,NaN,2016-01-28,17:40:16,2016-01-29,16:48:41,2016-01-25,11:04:00
4,2016-01-25,11:04:13,2016-01-29,17:18:21,2016-01-30,12:33:02,2016-01-30,12:33:02,2016-01-28,17:40:16,2016-01-29,16:48:41,2016-01-25,11:04:00

In [277]:
def plot_time_line(df,title,x_axis,y_axis):

    data = [go.Scatter(
              x=df.index,
              y=df['COSTOOPE'])]
    
    layout = go.Layout(
        title=title,
        xaxis=dict(
            title=x_axis,
            titlefont=dict(
                family='Courier New, monospace',
                size=18,
                color='#7f7f7f'
            )
        ),
        yaxis=dict(
            title=y_axis,
            titlefont=dict(
                family='Courier New, monospace',
                size=18,
                color='#7f7f7f'
            )
        )
    )
    fig = go.Figure(data=data, layout=layout)
    return py.iplot(fig, filename=title)

In [278]:
def plot_time_line_two(df,df_,title,x_axis,y_axis):

    trace1 = go.Scatter(
        x=df.index,
        y=df['COSTOOPE'],
        name='2016'
    )
    trace2 = go.Scatter(
        x=df_.index,
        y=df_['COSTOOPE'],
        name='2017'
    )
    data = [trace1, trace2]
    
    layout = go.Layout(
        title=title,
        xaxis=dict(
            title=x_axis,
            titlefont=dict(
                family='Courier New, monospace',
                size=18,
                color='#7f7f7f'
            )
        ),
        yaxis=dict(
            title=y_axis,
            titlefont=dict(
                family='Courier New, monospace',
                size=18,
                color='#7f7f7f'
            )
        )
    )
    fig = go.Figure(data=data, layout=layout)
    return py.iplot(fig, filename=title)

### Convertimos los formatos de Fecha y Hora

In [279]:
df['TIMESTAMP'] = pd.to_datetime(df['FECHA'] + ' ' + df['HORA'])
df

,NROFAVE,CODCLI,CODPP,CODOPE,CANVEN,CANOPE,COSTOOPE,COSTOOPEC,TICKET,NROTICKC,...,FECHAFTT,HORAFTT,FECHAIOPE,HORAIOPE,FECHAFOPE,HORAFOPE,IDPROTICKETS,FECHA,HORA,TIMESTAMP
0,PE00000001,057,CANOA CONFORT AL CORTE,EMPLANTILLADO,12.0,12.0,400.0,400.0,10003201001,1,...,2016-01-29,16:48:41,2016-01-28,17:40:16,2016-01-29,16:48:41,1,2016-01-25,11:04:00,2016-01-25 11:04:00
1,PE00000001,057,CANOA CONFORT AL CORTE,MONTADOR,12.0,12.0,1400.0,1400.0,10003202001,1,...,2016-01-29,13:41:54,2016-01-28,17:40:16,2016-01-29,16:48:41,2,2016-01-25,11:04:00,2016-01-25 11:04:00
2,PE00000001,057,CANOA CONFORT AL CORTE,COSTURA,12.0,12.0,450.0,450.0,10003203001,1,...,2016-01-29,18:29:57,2016-01-28,17:40:16,2016-01-29,16:48:41,3,2016-01-25,11:04:00,2016-01-25 11:04:00
3,PE00000001,057,CANOA CONFORT AL CORTE,ARMADO,12.0,12.0,1200.0,1200.0,10003204001,1,...,2016-01-29,18:47:44,2016-01-28,17:40:16,2016-01-29,16:48:41,4,2016-01-25,11:04:00,2016-01-25 11:04:00
4,PE00000001,057,CANOA CONFORT AL CORTE,CORTADO,12.0,12.0,200.0,200.0,10003205001,1,...,2016-01-30,12:33:02,2016-01-28,17:40:16,2016-01-29,16:48:41,5,2016-01-25,11:04:00,2016-01-25 11:04:00
5,PE00000001,057,CANOA CONFORT AL CORTE,ESTAMPADO,12.0,12.0,200.0,200.0,10003206001,1,...,2008-01-01,NaN,2016-01-28,17:40:16,2016-01-29,16:48:41,6,2016-01-25,11:04:00,2016-01-25 11:04:00
6,PE00000001,057,CANOA CONFORT AL CORTE,SELLOS,12.0,12.0,0.0,0.0,10003207001,1,...,2008-01-01,NaN,2016-01-28,17:40:16,2016-01-29,16:48:41,7,2016-01-25,11:04:00,2016-01-25 11:04:00
7,PE00000001,057,CANOA CONFORT AL CORTE,FORRADO DE PLANTA,12.0,12.0,500.0,500.0,10003208001,1,...,2016-01-28,17:40:16,2016-01-28,17:40:16,2016-01-29,16:48:41,8,2016-01-25,11:04:00,2016-01-25 11:04:00
8,PE00000001,057,CANOA CONFORT AL CORTE,PLANTILLAS,12.0,12.0,0.0,0.0,10003209001,1,...,2008-01-01,NaN,2016-01-28,17:40:16,2016-01-29,16:48:41,9,2016-01-25,11:04:00,2016-01-25 11:04:00
9,PE00000001,057,CANOA CONFORT AL CORTE,EMPLANTILLADO,12.0,12.0,400.0,400.0,10003201002,2,...,2016-01-29,16:49:17,2016-01-28,17:40:11,2016-01-29,16:49:17,10,2016-01-25,11:04:00,2016-01-25 11:04:00
10,PE00000001,057,CANOA CONFORT AL CORTE,MONTADOR,12.0,12.0,1400.0,1400.0,10003202002,2,...,2016-01-29,14:00:02,2016-01-28,17:40:11,2016-01-29,16:49:17,11,2016-01-25,11:04:00,2016-01-25 11:04:00
11,PE00000001,057,CANOA CONFORT AL CORTE,COSTURA,12.0,12.0,450.0,450.0,10003203002,2,...,2016-01-29,18:29:43,2016-01-28,17:40:11,2016-01-29,16:49:17,12,2016-01-25,11:04:00,2016-01-25 11:04:00
12,PE00000001,057,CANOA CONFORT AL CORTE,ARMADO,12.0,12.0,1200.0,1200.0,10003204002,2,...,2016-01-29,18:47:40,2016-01-28,17:40:11,2016-01-29,16:49:17,13,2016-01-25,11:04:00,2016-01-25 11:04:00
13,PE00000001,057,CANOA CONFORT AL CORTE,CORTADO,12.0,12.0,200.0,200.0,10003205002,2,...,2016-01-30,12:33:04,2016-01-28,17:40:11,2016-01-29,16:49:17,14,2016-01-25,11:04:00,2016-01-25 11:04:00
14,PE00000001,057,CANOA CONFORT AL CORTE,ESTAMPADO,12.0,12.0,200.0,200.0,10003206002,2,...,2008-01-01,NaN,2016-01-28,17:40:11,2016-01-29,16:49:17,15,2016-01-25,11:04:00,2016-01-25 11:04:00
15,PE00000001,057,CANOA CONFORT AL CORTE,SELLOS,12.0,12.0,0.0,0.0,10003207002,2,...,2008-01-01,NaN,2016-01-28,17:40:11,2016-01-29,16:49:17,16,2016-01-25,11:04:00,2016-01-25 11:04:00
16,PE00000001,057,CANOA CONFORT AL CORTE,FORRADO DE PLANTA,12.0,12.0,500.0,500.0,10003208002,2,...,2016-01-28,17:40:11,2016-01-28,17:40:11,2016-01-29,16:49:17,17,2016-01-25,11:04:00,2016-01-25 11:04:00
17,PE00000001,057,CANOA CONFORT AL CORTE,PLANTILLAS,12.0,12.0,0.0,0.0,10003209002,2,...,2008-01-01,NaN,2016-01-28,17:40:11,2016-01-29,16:49:17,18,2016-01-25,11:04:00,2016-01-25 11:04:00
18,PE00000001,057,CANOA CONFORT AL CORTE,EMPLANTILLADO,10.0,10.0,400.0,400.0,10003201003,3,...,2016-01-29,16:46:58,2016-01-28,17:41:23,2016-01-29,16:46:58,19,2016-01-25,11:04:00,2016-01-25 11:04:00
19,PE00000001,057,CANOA CONFORT AL CORTE,MONTADOR,10.0,10.0,1400.0,1400.0,10003202003,3,...,2016-01-29,13:42:07,2016-01-28,17:41:23,2016-01-29,16:46:58,20,2016-01-25,11:04:00,2016-01-25 11:04:00
20,PE00000001,057,CANOA CONFORT AL CORTE,COSTURA,10.0,10.0,450.0,450.0,10003203003,3,...,2016-01-29,18:28:46,2016-01-28,17:41:23,2016-01-29,16:46:58,21,2016-01-25,11:04:00,2016-01-25 11:04:00
21,PE00000001,057,CANOA CONFORT AL CORTE,ARMADO,10.0,10.0,1200.0,1200.0,10003204003,3,...,2016-01-30,12:49:22,2016-01-28,17:41:23,2016-01-29,16:46:58,22,2016-01-25,11:04:00,2016-01-25 11:04:00
22,PE00000001,057,CANOA CONFORT AL CORTE,CORTADO,10.0,10.0,200.0,200.0,10003205003,3,...,2016-01-30,12:33:23,2016-01-28,17:41:23,2016-01-29,16:46:58,23,2016-01-25,11:04:00,2016-01-25 11:04:00
23,PE00000001,057,CANOA CONFORT AL CORTE,ESTAMPADO,10.0,10.0,200.0,200.0,10003206003,3,...,2008-01-01,NaN,2016-01-28,17:41:23,2016-01-29,16:46:58,24,2016-01-25,11:04:00,2016-01-25 11:04:00
24,PE00000001,057,CANOA CONFORT AL CORTE,SELLOS,10.0,10.0,0.0,0.0,10003207003,3,...,2008-01-01,NaN,2016-01-28,17:41:23,2016-01-29,16:46:58,25,2016-01-25,11:04:00,2016-01-25 11:04:00
25,PE00000001,057,CANOA CONFORT AL CORTE,FORRADO DE PLANTA,10.0,10.0,500.0,500.0,10003208003,3,...,2016-01-28,17:41:23,2016-01-28,17:41:23,2016-01-29,16:46:58,26,2016-01-25,11:04:00,2016-01-25 11:04:00
26,PE00000001,057,CANOA CONFORT AL CORTE,PLANTILLAS,10.0,10.0,0.0,0.0,10003209003,3,...,2008-01-01,NaN,2016-01-28,17:41:23,2016-01-29,16:46:58,27,2016-01-25,11:04:00,2016-01-25 11:04:00
27,PE00000002,154,CANOA CONFORT AL CORTE,EMPLANTILLADO,12.0,12.0,400.0,400.0,10003301001,4,...,2016-01-29,16:47:55,2016-01-28,17:38:49,2016-01-29,16:47:55,28,2016-01-25,11:04:32,2016-01-25 11:04:32
28,PE00000002,154,CANOA CONFORT AL CORTE,MONTADOR,12.0,12.0,1400.0,1400.0,10003302001,4,...,2016-01-30,10:50:37,2016-01-28,17:38:49,2016-01-29,16:47:55,29,2016-01-25,11:04:32,2016-01-25 11:04:32
29,PE00000002,154,CANOA CONFORT AL CORTE,COSTURA,12.0,12.0,450.0,450.0,10003303001,4,...,2016-01-29,18:29:46,2016-01-28,17:38:49,2016-01-29,16:47:55,30,2016-01-25,11:04:32,2016-01-25 11:04:32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113798,PE00002193,053,PLANA HERRAJE 2017,COSTURA,13.0,13.0,520.0,520.0,10747903008,15340,...,2008-01-01,NaN,2008-01-01,NaN,2008-01-01,NaN,113808,2017-10-13,15:10:10,2017-10-13 15:10:10
113799,PE00002193,053,PLANA HERRAJE 2017,ARMADO,13.0,13.0,1350.0,1350.0,10747904008,15340,...,2008-01-01,NaN,2008-01-01,NaN,2008-01-01,NaN,113809,2017-10-13,15:10:10,2017-10-13 15:10:10
113800,PE00002193,053,PLANA HERRAJE 2017,CORTADO,13.0,13.0,400.0,400.0,10747905008,15340,...,2008-01-01,NaN,2008-01-01,NaN,2008-01-01,NaN,113810,2017-10-13,15:10:10,2017-10-13 15:10:10
113801,PE00002193,053,PLANA HERRAJE 2017,SUELAS,13.0,13.0,200.0,200.0,10747906008,15340,...,2008-01-01,NaN,2008-01-01,NaN,2008-01-01,NaN,113811,2017-10-13,15:10:10,2017-10-13 15:10:10
113802,PE00002193,053,PLANA HERRAJE 2017,LASER,13.0,13.0,0.0,0.0,10747907008,15340,...,2008-01-01,NaN,2008-01-01,NaN,2008-01-01,NaN,113812,2017-10-13,15:10:10,2017-10-13 15:10:10
113803,PE00002193,053,PLANA HERRAJE 2017,PLANTILLAS,13.0,13.0,0.0,0.0,10747908008,15340,...,2008-01-01,NaN,2008-01-01,NaN,2008-01-01,NaN,113813,2017-10-13,15:10:10,2017-10-13 15:10:10
113804,PE00002193,053,PLANA HERRAJE 2017,EMPLANTILLADO,13.0,13.0,400.0,400.0,10747901009,15341,...,2008-01-01,NaN,2008-01-01,NaN,2008-01-01,NaN,113814,2017-10-13,15:10:10,2017-10-13 15:10:10
113805,PE00002193,053,PLANA HERRAJE 2017,MONTADOR,13.0,13.0,1450.0,1450.0,10747902009,15341,...,2008-01-01,NaN,2008-01-01,NaN,2008-01-01,NaN,113815,2017-10-13,15:10:10,2017-10-13 15:10:10
113806,PE00002193,053,PLANA HERRAJE 2017,COSTURA,13.0,13.0,520.0,520.0,10747903009,15341,...,2008-01-01,NaN,2008-01-01,NaN,2008-01-01,NaN,113816,2017-10-13,15:10:10,2017-10-13 15:10:10
113807,PE00002193,053,PLANA HERRAJE 2017,ARMADO,13.0,13.0,1350.0,1350.0,10747904009,15341,...,2008-01-01,NaN,2008-01-01,NaN,2008-01-01,NaN,113817,2017-10-13,15:10:11,2017-10-13 15:10:11
113808,PE00002193,053,PLANA HERRAJE 2017,CORTADO,13.0,13.0,400.0,400.0,10747905009,15341,...,2008-01-01,NaN,2008-01-01,NaN,2008-01-01,NaN,113818,2017-10-13,15:10:11,2017-10-13 15:10:11
113809,PE00002193,053,PLANA HERRAJE 2017,SUELAS,13.0,13.0,200.0,200.0,10747906009,15341,...,2008-01-01,NaN,2008-01-01,NaN,2008-01-01,NaN,113819,2017-10-13,15:10:11,2017-10-13 15:10:11
113810,PE00002193,053,PLANA HERRAJE 2017,LASER,13.0,13.0,0.0,0.0,10747907009,15341,...,2008-01-01,NaN,2008-01-01,NaN,2008-01-01,NaN,113820,2017-10-13,15:10:11,2017-10-13 15:10:11
113811,PE00002193,053,PLANA HERRAJE 2017,PLANTILLAS,13.0,13.0,0.0,0.0,10747908009,15341,...,2008-01-01,NaN,2008-01-01,NaN,2008-01-01,NaN,113821,2017-10-13,15:10:11,2017-10-13 15:10:11
113812,PE00002193,053,PLANA HERRAJE 2017,EMPLANTILLADO,13.0,13.0,400.0,400.0,10747901010,15342,...,2008-01-01,NaN,2008-01-01,NaN,2008-01-01,NaN,113822,2017-10-13,15:10:11,2017-10-13 15:10:11
113813,PE00002193,053,PLANA HERRAJE 2017,MONTADOR,13.0,13.0,1450.0,1450.0,10747902010,15342,...,2008-01-01,NaN,2008-01-01,NaN,2008-01-01,NaN,113823,2017-10-13,15:10:11,2017-10-13 15:10:11
113814,PE00002193,053,PLANA HERRAJE 2017,COSTURA,13.0,13.0,520.0,520.0,10747903010,15342,...,2008-01-01,NaN,2008-01-01,NaN,2008-01-01,NaN,113824,2017-10-13,15:10:11,2017-10-13 15:10:11
113815,PE00002193,053,PLANA HERRAJE 2017,ARMADO,13.0,13.0,1350.0,1350.0,10747904010,15342,...,2008-01-01,NaN,2008-01-01,NaN,2008-01-01,NaN,113825,2017-10-13,15:10:11,2017-10-13 15:10:11
113816,PE00002193,053,PLANA HERRAJE 2017,CORTADO,13.0,13.0,400.0,400.0,10747905010,15342,...,2008-01-01,NaN,2008-01-01,NaN,2008-01-01,NaN,113826,2017-10-13,15:10:12,2017-10-13 15:10:12
113817,PE00002193,053,PLANA HERRAJE 2017,SUELAS,13.0,13.0,200.0,200.0,10747906010,15342,...,2008-01-01,NaN,2008-01-01,NaN,2008-01-01,NaN,113827,2017-10-13,15:10:12,2017-10-13 15:10:12
113818,PE00002193,053,PLANA HERRAJE 2017,LASER,13.0,13.0,0.0,0.0,10747907010,15342,...,2008-01-01,NaN,2008-01-01,NaN,2008-01-01,NaN,113828,2017-10-13,15:10:12,2017-10-13 15:10:12
113819,PE00002193,053,PLANA HERRAJE 2017,PLANTILLAS,13.0,13.0,0.0,0.0,10747908010,15342,...,2008-01-01,NaN,2008-01-01,NaN,2008-01-01,NaN,113829,2017-10-13,15:10:12,2017-10-13 15:10:12
113820,PE00002193,053,LASER,EMPLANTILLADO,13.0,13.0,400.0,400.0,10747901011,15343,...,2008-01-01,NaN,2008-01-01,NaN,2008-01-01,NaN,113830,2017-10-13,15:10:12,2017-10-13 15:10:12
113821,PE00002193,053,LASER,MONTADOR,13.0,13.0,1450.0,1450.0,10747902011,15343,...,2008-01-01,NaN,2008-01-01,NaN,2008-01-01,NaN,113831,2017-10-13,15:10:12,2017-10-13 15:10:12
113822,PE00002193,053,LASER,COSTURA,13.0,13.0,520.0,520.0,10747903011,15343,...,2008-01-01,NaN,2008-01-01,NaN,2008-01-01,NaN,113832,2017-10-13,15:10:12,2017-10-13 15:10:12
113823,PE00002193,053,LASER,ARMADO,13.0,13.0,1250.0,1250.0,10747904011,15343,...,2008-01-01,NaN,2008-01-01,NaN,2008-01-01,NaN,113833,2017-10-13,15:10:12,2017-10-13 15:10:12
113824,PE00002193,053,LASER,CORTADO,13.0,13.0,400.0,400.0,10747905011,15343,...,2008-01-01,NaN,2008-01-01,NaN,2008-01-01,NaN,113834,2017-10-13,15:10:13,2017-10-13 15:10:13
113825,PE00002193,053,LASER,SUELAS,13.0,13.0,200.0,200.0,10747906011,15343,...,2008-01-01,NaN,2008-01-01,NaN,2008-01-01,NaN,113835,2017-10-13,15:10:13,2017-10-13 15:10:13
113826,PE00002193,053,LASER,PLANTILLAS,13.0,13.0,0.0,0.0,10747907011,15343,...,2008-01-01,NaN,2008-01-01,NaN,2008-01-01,NaN,113836,2017-10-13,15:10:13,2017-10-13 15:10:13
113827,PE00002193,053,LASER,LASER,13.0,13.0,0.0,0.0,10747908011,15343,...,2008-01-01,NaN,2008-01-01,NaN,2008-01-01,NaN,113837,2017-10-13,15:10:13,2017-10-13 15:10:13

## Filtramos por Año

Analizamos la cantidad de transacciones por cada año

In [280]:
df_temp = df.set_index('TIMESTAMP')['2016'].groupby('FECHA').count()
plot_time_line(df_temp,'2016','Tiempo','Registros')

In [281]:
df_temp_ = df.set_index('TIMESTAMP')['2017'].groupby('FECHA').count()
plot_time_line(df_temp_,'2017','Tiempo','Registros')

In [282]:
plot_time_line_two(df_temp,df_temp_,'2017 vs 2016','Tiempo','Registros')

## Filtramos por Mes

In [283]:
df.set_index('TIMESTAMP').groupby(pd.TimeGrouper(freq='M')).count()

,NROFAVE,CODCLI,CODPP,CODOPE,CANVEN,CANOPE,COSTOOPE,COSTOOPEC,TICKET,NROTICKC,...,HORAITT,FECHAFTT,HORAFTT,FECHAIOPE,HORAIOPE,FECHAFOPE,HORAFOPE,IDPROTICKETS,FECHA,HORA
TIMESTAMP,,,,,,,,,,,,,,,,,,,,,
2016-01-31,693,693,757,757,757,757,757,757,757,757,...,153,757,424,757,661,757,642,757,757,757
2016-02-29,4416,4416,4467,4467,4467,4467,4467,4467,4467,4467,...,1021,4467,2653,4467,3635,4467,3073,4467,4467,4467
2016-03-31,4379,4379,4438,4438,4438,4438,4438,4438,4438,4438,...,810,4438,3171,4438,4324,4438,4130,4438,4438,4438
2016-04-30,3683,3683,3755,3755,3755,3755,3755,3755,3755,3755,...,1024,3755,3004,3755,3580,3755,3378,3755,3755,3755
2016-05-31,2274,2274,2318,2318,2318,2318,2318,2318,2318,2318,...,648,2318,1894,2318,2267,2318,2090,2318,2318,2318
2016-06-30,4467,4467,4502,4502,4502,4502,4502,4502,4502,4502,...,1354,4502,3840,4502,4377,4502,3821,4502,4502,4502
2016-07-31,4304,4304,4336,4336,4336,4336,4336,4336,4336,4336,...,957,4336,3395,4336,3832,4336,3623,4336,4336,4336
2016-08-31,6754,6754,6802,6802,6802,6802,6802,6802,6802,6802,...,914,6802,5116,6802,5968,6802,5853,6802,6802,6802
2016-09-30,9104,9104,9196,9196,9196,9196,9196,9196,9196,9196,...,1074,9196,6113,9196,7867,9196,7656,9196,9196,9196
2016-10-31,8796,8796,8873,8873,8873,8873,8873,8873,8873,8873,...,1162,8873,6560,8873,8226,8873,8153,8873,8873,8873
2016-11-30,8531,8531,8708,8708,8708,8708,8708,8708,8708,8708,...,1066,8708,6074,8708,8036,8708,7534,8708,8708,8708
2016-12-31,2258,2258,2349,2349,2349,2349,2349,2349,2349,2349,...,250,2349,1319,2349,1957,2349,1840,2349,2349,2349
2017-01-31,590,590,635,635,635,635,635,635,635,635,...,81,635,432,635,590,635,590,635,635,635
2017-02-28,3548,3548,3576,3576,3576,3576,3576,3576,3576,3576,...,740,3576,3119,3576,3500,3576,3436,3576,3576,3576
2017-03-31,8026,8026,8094,8094,8094,8094,8094,8094,8094,8094,...,1211,8094,7019,8094,7786,8094,7714,8094,8094,8094
2017-04-30,4649,4649,4762,4762,4762,4762,4762,4762,4762,4762,...,541,4762,3152,4762,4328,4762,4232,4762,4762,4762
2017-05-31,4336,4336,4396,4396,4396,4396,4396,4396,4396,4396,...,579,4396,2964,4396,4224,4396,4171,4396,4396,4396
2017-06-30,3951,3951,3999,3999,3999,3999,3999,3999,3999,3999,...,469,3999,2698,3999,3811,3999,3719,3999,3999,3999
2017-07-31,6924,6924,6968,6968,6968,6968,6968,6968,6968,6968,...,806,6968,4418,6968,6485,6968,6270,6968,6968,6968
2017-08-31,4264,4264,4314,4314,4314,4314,4314,4314,4314,4314,...,508,4314,2642,4314,4176,4314,3936,4314,4314,4314
2017-09-30,11565,11565,11792,11792,11792,11792,11792,11792,11792,11792,...,2203,11792,6371,11792,9855,11792,9143,11792,11792,11792
2017-10-31,4448,4448,4791,4791,4791,4791,4791,4791,4791,4791,...,460,4791,482,4791,1912,4791,528,4791,4791,4791

In [284]:
df_temp_monthly = df.set_index('TIMESTAMP').groupby(pd.TimeGrouper(freq='M')).count()
plot_time_line(df_temp_monthly,'Mensual','Tiempo','Registros')

### Filtramos por Número de FAVE

Buscamos analizar el tiempo en realizar un pedido

In [285]:
df.loc[df['NROFAVE'] == 'PE00000001']

,NROFAVE,CODCLI,CODPP,CODOPE,CANVEN,CANOPE,COSTOOPE,COSTOOPEC,TICKET,NROTICKC,...,FECHAFTT,HORAFTT,FECHAIOPE,HORAIOPE,FECHAFOPE,HORAFOPE,IDPROTICKETS,FECHA,HORA,TIMESTAMP
0,PE00000001,057,CANOA CONFORT AL CORTE,EMPLANTILLADO,12.0,12.0,400.0,400.0,10003201001,1,...,2016-01-29,16:48:41,2016-01-28,17:40:16,2016-01-29,16:48:41,1,2016-01-25,11:04:00,2016-01-25 11:04:00
1,PE00000001,057,CANOA CONFORT AL CORTE,MONTADOR,12.0,12.0,1400.0,1400.0,10003202001,1,...,2016-01-29,13:41:54,2016-01-28,17:40:16,2016-01-29,16:48:41,2,2016-01-25,11:04:00,2016-01-25 11:04:00
2,PE00000001,057,CANOA CONFORT AL CORTE,COSTURA,12.0,12.0,450.0,450.0,10003203001,1,...,2016-01-29,18:29:57,2016-01-28,17:40:16,2016-01-29,16:48:41,3,2016-01-25,11:04:00,2016-01-25 11:04:00
3,PE00000001,057,CANOA CONFORT AL CORTE,ARMADO,12.0,12.0,1200.0,1200.0,10003204001,1,...,2016-01-29,18:47:44,2016-01-28,17:40:16,2016-01-29,16:48:41,4,2016-01-25,11:04:00,2016-01-25 11:04:00
4,PE00000001,057,CANOA CONFORT AL CORTE,CORTADO,12.0,12.0,200.0,200.0,10003205001,1,...,2016-01-30,12:33:02,2016-01-28,17:40:16,2016-01-29,16:48:41,5,2016-01-25,11:04:00,2016-01-25 11:04:00
5,PE00000001,057,CANOA CONFORT AL CORTE,ESTAMPADO,12.0,12.0,200.0,200.0,10003206001,1,...,2008-01-01,NaN,2016-01-28,17:40:16,2016-01-29,16:48:41,6,2016-01-25,11:04:00,2016-01-25 11:04:00
6,PE00000001,057,CANOA CONFORT AL CORTE,SELLOS,12.0,12.0,0.0,0.0,10003207001,1,...,2008-01-01,NaN,2016-01-28,17:40:16,2016-01-29,16:48:41,7,2016-01-25,11:04:00,2016-01-25 11:04:00
7,PE00000001,057,CANOA CONFORT AL CORTE,FORRADO DE PLANTA,12.0,12.0,500.0,500.0,10003208001,1,...,2016-01-28,17:40:16,2016-01-28,17:40:16,2016-01-29,16:48:41,8,2016-01-25,11:04:00,2016-01-25 11:04:00
8,PE00000001,057,CANOA CONFORT AL CORTE,PLANTILLAS,12.0,12.0,0.0,0.0,10003209001,1,...,2008-01-01,NaN,2016-01-28,17:40:16,2016-01-29,16:48:41,9,2016-01-25,11:04:00,2016-01-25 11:04:00
9,PE00000001,057,CANOA CONFORT AL CORTE,EMPLANTILLADO,12.0,12.0,400.0,400.0,10003201002,2,...,2016-01-29,16:49:17,2016-01-28,17:40:11,2016-01-29,16:49:17,10,2016-01-25,11:04:00,2016-01-25 11:04:00
10,PE00000001,057,CANOA CONFORT AL CORTE,MONTADOR,12.0,12.0,1400.0,1400.0,10003202002,2,...,2016-01-29,14:00:02,2016-01-28,17:40:11,2016-01-29,16:49:17,11,2016-01-25,11:04:00,2016-01-25 11:04:00
11,PE00000001,057,CANOA CONFORT AL CORTE,COSTURA,12.0,12.0,450.0,450.0,10003203002,2,...,2016-01-29,18:29:43,2016-01-28,17:40:11,2016-01-29,16:49:17,12,2016-01-25,11:04:00,2016-01-25 11:04:00
12,PE00000001,057,CANOA CONFORT AL CORTE,ARMADO,12.0,12.0,1200.0,1200.0,10003204002,2,...,2016-01-29,18:47:40,2016-01-28,17:40:11,2016-01-29,16:49:17,13,2016-01-25,11:04:00,2016-01-25 11:04:00
13,PE00000001,057,CANOA CONFORT AL CORTE,CORTADO,12.0,12.0,200.0,200.0,10003205002,2,...,2016-01-30,12:33:04,2016-01-28,17:40:11,2016-01-29,16:49:17,14,2016-01-25,11:04:00,2016-01-25 11:04:00
14,PE00000001,057,CANOA CONFORT AL CORTE,ESTAMPADO,12.0,12.0,200.0,200.0,10003206002,2,...,2008-01-01,NaN,2016-01-28,17:40:11,2016-01-29,16:49:17,15,2016-01-25,11:04:00,2016-01-25 11:04:00
15,PE00000001,057,CANOA CONFORT AL CORTE,SELLOS,12.0,12.0,0.0,0.0,10003207002,2,...,2008-01-01,NaN,2016-01-28,17:40:11,2016-01-29,16:49:17,16,2016-01-25,11:04:00,2016-01-25 11:04:00
16,PE00000001,057,CANOA CONFORT AL CORTE,FORRADO DE PLANTA,12.0,12.0,500.0,500.0,10003208002,2,...,2016-01-28,17:40:11,2016-01-28,17:40:11,2016-01-29,16:49:17,17,2016-01-25,11:04:00,2016-01-25 11:04:00
17,PE00000001,057,CANOA CONFORT AL CORTE,PLANTILLAS,12.0,12.0,0.0,0.0,10003209002,2,...,2008-01-01,NaN,2016-01-28,17:40:11,2016-01-29,16:49:17,18,2016-01-25,11:04:00,2016-01-25 11:04:00
18,PE00000001,057,CANOA CONFORT AL CORTE,EMPLANTILLADO,10.0,10.0,400.0,400.0,10003201003,3,...,2016-01-29,16:46:58,2016-01-28,17:41:23,2016-01-29,16:46:58,19,2016-01-25,11:04:00,2016-01-25 11:04:00
19,PE00000001,057,CANOA CONFORT AL CORTE,MONTADOR,10.0,10.0,1400.0,1400.0,10003202003,3,...,2016-01-29,13:42:07,2016-01-28,17:41:23,2016-01-29,16:46:58,20,2016-01-25,11:04:00,2016-01-25 11:04:00
20,PE00000001,057,CANOA CONFORT AL CORTE,COSTURA,10.0,10.0,450.0,450.0,10003203003,3,...,2016-01-29,18:28:46,2016-01-28,17:41:23,2016-01-29,16:46:58,21,2016-01-25,11:04:00,2016-01-25 11:04:00
21,PE00000001,057,CANOA CONFORT AL CORTE,ARMADO,10.0,10.0,1200.0,1200.0,10003204003,3,...,2016-01-30,12:49:22,2016-01-28,17:41:23,2016-01-29,16:46:58,22,2016-01-25,11:04:00,2016-01-25 11:04:00
22,PE00000001,057,CANOA CONFORT AL CORTE,CORTADO,10.0,10.0,200.0,200.0,10003205003,3,...,2016-01-30,12:33:23,2016-01-28,17:41:23,2016-01-29,16:46:58,23,2016-01-25,11:04:00,2016-01-25 11:04:00
23,PE00000001,057,CANOA CONFORT AL CORTE,ESTAMPADO,10.0,10.0,200.0,200.0,10003206003,3,...,2008-01-01,NaN,2016-01-28,17:41:23,2016-01-29,16:46:58,24,2016-01-25,11:04:00,2016-01-25 11:04:00
24,PE00000001,057,CANOA CONFORT AL CORTE,SELLOS,10.0,10.0,0.0,0.0,10003207003,3,...,2008-01-01,NaN,2016-01-28,17:41:23,2016-01-29,16:46:58,25,2016-01-25,11:04:00,2016-01-25 11:04:00
25,PE00000001,057,CANOA CONFORT AL CORTE,FORRADO DE PLANTA,10.0,10.0,500.0,500.0,10003208003,3,...,2016-01-28,17:41:23,2016-01-28,17:41:23,2016-01-29,16:46:58,26,2016-01-25,11:04:00,2016-01-25 11:04:00
26,PE00000001,057,CANOA CONFORT AL CORTE,PLANTILLAS,10.0,10.0,0.0,0.0,10003209003,3,...,2008-01-01,NaN,2016-01-28,17:41:23,2016-01-29,16:46:58,27,2016-01-25,11:04:00,2016-01-25 11:04:00

### Convertimos el Inicio y Fin de las Operaciones

In [286]:
df['TIMEIOPE'] = pd.to_datetime(df['FECHAIOPE'] + ' ' + df['HORAIOPE'])
df['TIMEFOPE'] = pd.to_datetime(df['FECHAFOPE'] + ' ' + df['HORAFOPE'])
df

,NROFAVE,CODCLI,CODPP,CODOPE,CANVEN,CANOPE,COSTOOPE,COSTOOPEC,TICKET,NROTICKC,...,FECHAIOPE,HORAIOPE,FECHAFOPE,HORAFOPE,IDPROTICKETS,FECHA,HORA,TIMESTAMP,TIMEIOPE,TIMEFOPE
0,PE00000001,057,CANOA CONFORT AL CORTE,EMPLANTILLADO,12.0,12.0,400.0,400.0,10003201001,1,...,2016-01-28,17:40:16,2016-01-29,16:48:41,1,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:16,2016-01-29 16:48:41
1,PE00000001,057,CANOA CONFORT AL CORTE,MONTADOR,12.0,12.0,1400.0,1400.0,10003202001,1,...,2016-01-28,17:40:16,2016-01-29,16:48:41,2,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:16,2016-01-29 16:48:41
2,PE00000001,057,CANOA CONFORT AL CORTE,COSTURA,12.0,12.0,450.0,450.0,10003203001,1,...,2016-01-28,17:40:16,2016-01-29,16:48:41,3,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:16,2016-01-29 16:48:41
3,PE00000001,057,CANOA CONFORT AL CORTE,ARMADO,12.0,12.0,1200.0,1200.0,10003204001,1,...,2016-01-28,17:40:16,2016-01-29,16:48:41,4,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:16,2016-01-29 16:48:41
4,PE00000001,057,CANOA CONFORT AL CORTE,CORTADO,12.0,12.0,200.0,200.0,10003205001,1,...,2016-01-28,17:40:16,2016-01-29,16:48:41,5,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:16,2016-01-29 16:48:41
5,PE00000001,057,CANOA CONFORT AL CORTE,ESTAMPADO,12.0,12.0,200.0,200.0,10003206001,1,...,2016-01-28,17:40:16,2016-01-29,16:48:41,6,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:16,2016-01-29 16:48:41
6,PE00000001,057,CANOA CONFORT AL CORTE,SELLOS,12.0,12.0,0.0,0.0,10003207001,1,...,2016-01-28,17:40:16,2016-01-29,16:48:41,7,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:16,2016-01-29 16:48:41
7,PE00000001,057,CANOA CONFORT AL CORTE,FORRADO DE PLANTA,12.0,12.0,500.0,500.0,10003208001,1,...,2016-01-28,17:40:16,2016-01-29,16:48:41,8,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:16,2016-01-29 16:48:41
8,PE00000001,057,CANOA CONFORT AL CORTE,PLANTILLAS,12.0,12.0,0.0,0.0,10003209001,1,...,2016-01-28,17:40:16,2016-01-29,16:48:41,9,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:16,2016-01-29 16:48:41
9,PE00000001,057,CANOA CONFORT AL CORTE,EMPLANTILLADO,12.0,12.0,400.0,400.0,10003201002,2,...,2016-01-28,17:40:11,2016-01-29,16:49:17,10,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:11,2016-01-29 16:49:17
10,PE00000001,057,CANOA CONFORT AL CORTE,MONTADOR,12.0,12.0,1400.0,1400.0,10003202002,2,...,2016-01-28,17:40:11,2016-01-29,16:49:17,11,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:11,2016-01-29 16:49:17
11,PE00000001,057,CANOA CONFORT AL CORTE,COSTURA,12.0,12.0,450.0,450.0,10003203002,2,...,2016-01-28,17:40:11,2016-01-29,16:49:17,12,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:11,2016-01-29 16:49:17
12,PE00000001,057,CANOA CONFORT AL CORTE,ARMADO,12.0,12.0,1200.0,1200.0,10003204002,2,...,2016-01-28,17:40:11,2016-01-29,16:49:17,13,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:11,2016-01-29 16:49:17
13,PE00000001,057,CANOA CONFORT AL CORTE,CORTADO,12.0,12.0,200.0,200.0,10003205002,2,...,2016-01-28,17:40:11,2016-01-29,16:49:17,14,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:11,2016-01-29 16:49:17
14,PE00000001,057,CANOA CONFORT AL CORTE,ESTAMPADO,12.0,12.0,200.0,200.0,10003206002,2,...,2016-01-28,17:40:11,2016-01-29,16:49:17,15,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:11,2016-01-29 16:49:17
15,PE00000001,057,CANOA CONFORT AL CORTE,SELLOS,12.0,12.0,0.0,0.0,10003207002,2,...,2016-01-28,17:40:11,2016-01-29,16:49:17,16,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:11,2016-01-29 16:49:17
16,PE00000001,057,CANOA CONFORT AL CORTE,FORRADO DE PLANTA,12.0,12.0,500.0,500.0,10003208002,2,...,2016-01-28,17:40:11,2016-01-29,16:49:17,17,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:11,2016-01-29 16:49:17
17,PE00000001,057,CANOA CONFORT AL CORTE,PLANTILLAS,12.0,12.0,0.0,0.0,10003209002,2,...,2016-01-28,17:40:11,2016-01-29,16:49:17,18,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:11,2016-01-29 16:49:17
18,PE00000001,057,CANOA CONFORT AL CORTE,EMPLANTILLADO,10.0,10.0,400.0,400.0,10003201003,3,...,2016-01-28,17:41:23,2016-01-29,16:46:58,19,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:41:23,2016-01-29 16:46:58
19,PE00000001,057,CANOA CONFORT AL CORTE,MONTADOR,10.0,10.0,1400.0,1400.0,10003202003,3,...,2016-01-28,17:41:23,2016-01-29,16:46:58,20,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:41:23,2016-01-29 16:46:58
20,PE00000001,057,CANOA CONFORT AL CORTE,COSTURA,10.0,10.0,450.0,450.0,10003203003,3,...,2016-01-28,17:41:23,2016-01-29,16:46:58,21,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:41:23,2016-01-29 16:46:58
21,PE00000001,057,CANOA CONFORT AL CORTE,ARMADO,10.0,10.0,1200.0,1200.0,10003204003,3,...,2016-01-28,17:41:23,2016-01-29,16:46:58,22,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:41:23,2016-01-29 16:46:58
22,PE00000001,057,CANOA CONFORT AL CORTE,CORTADO,10.0,10.0,200.0,200.0,10003205003,3,...,2016-01-28,17:41:23,2016-01-29,16:46:58,23,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:41:23,2016-01-29 16:46:58
23,PE00000001,057,CANOA CONFORT AL CORTE,ESTAMPADO,10.0,10.0,200.0,200.0,10003206003,3,...,2016-01-28,17:41:23,2016-01-29,16:46:58,24,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:41:23,2016-01-29 16:46:58
24,PE00000001,057,CANOA CONFORT AL CORTE,SELLOS,10.0,10.0,0.0,0.0,10003207003,3,...,2016-01-28,17:41:23,2016-01-29,16:46:58,25,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:41:23,2016-01-29 16:46:58
25,PE00000001,057,CANOA CONFORT AL CORTE,FORRADO DE PLANTA,10.0,10.0,500.0,500.0,10003208003,3,...,2016-01-28,17:41:23,2016-01-29,16:46:58,26,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:41:23,2016-01-29 16:46:58
26,PE00000001,057,CANOA CONFORT AL CORTE,PLANTILLAS,10.0,10.0,0.0,0.0,10003209003,3,...,2016-01-28,17:41:23,2016-01-29,16:46:58,27,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:41:23,2016-01-29 16:46:58
27,PE00000002,154,CANOA CONFORT AL CORTE,EMPLANTILLADO,12.0,12.0,400.0,400.0,10003301001,4,...,2016-01-28,17:38:49,2016-01-29,16:47:55,28,2016-01-25,11:04:32,2016-01-25 11:04:32,2016-01-28 17:38:49,2016-01-29 16:47:55
28,PE00000002,154,CANOA CONFORT AL CORTE,MONTADOR,12.0,12.0,1400.0,1400.0,10003302001,4,...,2016-01-28,17:38:49,2016-01-29,16:47:55,29,2016-01-25,11:04:32,2016-01-25 11:04:32,2016-01-28 17:38:49,2016-01-29 16:47:55
29,PE00000002,154,CANOA CONFORT AL CORTE,COSTURA,12.0,12.0,450.0,450.0,10003303001,4,...,2016-01-28,17:38:49,2016-01-29,16:47:55,30,2016-01-25,11:04:32,2016-01-25 11:04:32,2016-01-28 17:38:49,2016-01-29 16:47:55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113798,PE00002193,053,PLANA HERRAJE 2017,COSTURA,13.0,13.0,520.0,520.0,10747903008,15340,...,2008-01-01,NaN,2008-01-01,NaN,113808,2017-10-13,15:10:10,2017-10-13 15:10:10,NaT,NaT
113799,PE00002193,053,PLANA HERRAJE 2017,ARMADO,13.0,13.0,1350.0,1350.0,10747904008,15340,...,2008-01-01,NaN,2008-01-01,NaN,113809,2017-10-13,15:10:10,2017-10-13 15:10:10,NaT,NaT
113800,PE00002193,053,PLANA HERRAJE 2017,CORTADO,13.0,13.0,400.0,400.0,10747905008,15340,...,2008-01-01,NaN,2008-01-01,NaN,113810,2017-10-13,15:10:10,2017-10-13 15:10:10,NaT,NaT
113801,PE00002193,053,PLANA HERRAJE 2017,SUELAS,13.0,13.0,200.0,200.0,10747906008,15340,...,2008-01-01,NaN,2008-01-01,NaN,113811,2017-10-13,15:10:10,2017-10-13 15:10:10,NaT,NaT
113802,PE00002193,053,PLANA HERRAJE 2017,LASER,13.0,13.0,0.0,0.0,10747907008,15340,...,2008-01-01,NaN,2008-01-01,NaN,113812,2017-10-13,15:10:10,2017-10-13 15:10:10,NaT,NaT
113803,PE00002193,053,PLANA HERRAJE 2017,PLANTILLAS,13.0,13.0,0.0,0.0,10747908008,15340,...,2008-01-01,NaN,2008-01-01,NaN,113813,2017-10-13,15:10:10,2017-10-13 15:10:10,NaT,NaT
113804,PE00002193,053,PLANA HERRAJE 2017,EMPLANTILLADO,13.0,13.0,400.0,400.0,10747901009,15341,...,2008-01-01,NaN,2008-01-01,NaN,113814,2017-10-13,15:10:10,2017-10-13 15:10:10,NaT,NaT
113805,PE00002193,053,PLANA HERRAJE 2017,MONTADOR,13.0,13.0,1450.0,1450.0,10747902009,15341,...,2008-01-01,NaN,2008-01-01,NaN,113815,2017-10-13,15:10:10,2017-10-13 15:10:10,NaT,NaT
113806,PE00002193,053,PLANA HERRAJE 2017,COSTURA,13.0,13.0,520.0,520.0,10747903009,15341,...,2008-01-01,NaN,2008-01-01,NaN,113816,2017-10-13,15:10:10,2017-10-13 15:10:10,NaT,NaT
113807,PE00002193,053,PLANA HERRAJE 2017,ARMADO,13.0,13.0,1350.0,1350.0,10747904009,15341,...,2008-01-01,NaN,2008-01-01,NaN,113817,2017-10-13,15:10:11,2017-10-13 15:10:11,NaT,NaT
113808,PE00002193,053,PLANA HERRAJE 2017,CORTADO,13.0,13.0,400.0,400.0,10747905009,15341,...,2008-01-01,NaN,2008-01-01,NaN,113818,2017-10-13,15:10:11,2017-10-13 15:10:11,NaT,NaT
113809,PE00002193,053,PLANA HERRAJE 2017,SUELAS,13.0,13.0,200.0,200.0,10747906009,15341,...,2008-01-01,NaN,2008-01-01,NaN,113819,2017-10-13,15:10:11,2017-10-13 15:10:11,NaT,NaT
113810,PE00002193,053,PLANA HERRAJE 2017,LASER,13.0,13.0,0.0,0.0,10747907009,15341,...,2008-01-01,NaN,2008-01-01,NaN,113820,2017-10-13,15:10:11,2017-10-13 15:10:11,NaT,NaT
113811,PE00002193,053,PLANA HERRAJE 2017,PLANTILLAS,13.0,13.0,0.0,0.0,10747908009,15341,...,2008-01-01,NaN,2008-01-01,NaN,113821,2017-10-13,15:10:11,2017-10-13 15:10:11,NaT,NaT
113812,PE00002193,053,PLANA HERRAJE 2017,EMPLANTILLADO,13.0,13.0,400.0,400.0,10747901010,15342,...,2008-01-01,NaN,2008-01-01,NaN,113822,2017-10-13,15:10:11,2017-10-13 15:10:11,NaT,NaT
113813,PE00002193,053,PLANA HERRAJE 2017,MONTADOR,13.0,13.0,1450.0,1450.0,10747902010,15342,...,2008-01-01,NaN,2008-01-01,NaN,113823,2017-10-13,15:10:11,2017-10-13 15:10:11,NaT,NaT
113814,PE00002193,053,PLANA HERRAJE 2017,COSTURA,13.0,13.0,520.0,520.0,10747903010,15342,...,2008-01-01,NaN,2008-01-01,NaN,113824,2017-10-13,15:10:11,2017-10-13 15:10:11,NaT,NaT
113815,PE00002193,053,PLANA HERRAJE 2017,ARMADO,13.0,13.0,1350.0,1350.0,10747904010,15342,...,2008-01-01,NaN,2008-01-01,NaN,113825,2017-10-13,15:10:11,2017-10-13 15:10:11,NaT,NaT
113816,PE00002193,053,PLANA HERRAJE 2017,CORTADO,13.0,13.0,400.0,400.0,10747905010,15342,...,2008-01-01,NaN,2008-01-01,NaN,113826,2017-10-13,15:10:12,2017-10-13 15:10:12,NaT,NaT
113817,PE00002193,053,PLANA HERRAJE 2017,SUELAS,13.0,13.0,200.0,200.0,10747906010,15342,...,2008-01-01,NaN,2008-01-01,NaN,113827,2017-10-13,15:10:12,2017-10-13 15:10:12,NaT,NaT
113818,PE00002193,053,PLANA HERRAJE 2017,LASER,13.0,13.0,0.0,0.0,10747907010,15342,...,2008-01-01,NaN,2008-01-01,NaN,113828,2017-10-13,15:10:12,2017-10-13 15:10:12,NaT,NaT
113819,PE00002193,053,PLANA HERRAJE 2017,PLANTILLAS,13.0,13.0,0.0,0.0,10747908010,15342,...,2008-01-01,NaN,2008-01-01,NaN,113829,2017-10-13,15:10:12,2017-10-13 15:10:12,NaT,NaT
113820,PE00002193,053,LASER,EMPLANTILLADO,13.0,13.0,400.0,400.0,10747901011,15343,...,2008-01-01,NaN,2008-01-01,NaN,113830,2017-10-13,15:10:12,2017-10-13 15:10:12,NaT,NaT
113821,PE00002193,053,LASER,MONTADOR,13.0,13.0,1450.0,1450.0,10747902011,15343,...,2008-01-01,NaN,2008-01-01,NaN,113831,2017-10-13,15:10:12,2017-10-13 15:10:12,NaT,NaT
113822,PE00002193,053,LASER,COSTURA,13.0,13.0,520.0,520.0,10747903011,15343,...,2008-01-01,NaN,2008-01-01,NaN,113832,2017-10-13,15:10:12,2017-10-13 15:10:12,NaT,NaT
113823,PE00002193,053,LASER,ARMADO,13.0,13.0,1250.0,1250.0,10747904011,15343,...,2008-01-01,NaN,2008-01-01,NaN,113833,2017-10-13,15:10:12,2017-10-13 15:10:12,NaT,NaT
113824,PE00002193,053,LASER,CORTADO,13.0,13.0,400.0,400.0,10747905011,15343,...,2008-01-01,NaN,2008-01-01,NaN,113834,2017-10-13,15:10:13,2017-10-13 15:10:13,NaT,NaT
113825,PE00002193,053,LASER,SUELAS,13.0,13.0,200.0,200.0,10747906011,15343,...,2008-01-01,NaN,2008-01-01,NaN,113835,2017-10-13,15:10:13,2017-10-13 15:10:13,NaT,NaT
113826,PE00002193,053,LASER,PLANTILLAS,13.0,13.0,0.0,0.0,10747907011,15343,...,2008-01-01,NaN,2008-01-01,NaN,113836,2017-10-13,15:10:13,2017-10-13 15:10:13,NaT,NaT
113827,PE00002193,053,LASER,LASER,13.0,13.0,0.0,0.0,10747908011,15343,...,2008-01-01,NaN,2008-01-01,NaN,113837,2017-10-13,15:10:13,2017-10-13 15:10:13,NaT,NaT

Calculamos la diferencia buscando determinar el rendimiento de los operadores

In [287]:
df['TIMEDIF'] = df['TIMEFOPE'] - df['TIMEIOPE']
df

,NROFAVE,CODCLI,CODPP,CODOPE,CANVEN,CANOPE,COSTOOPE,COSTOOPEC,TICKET,NROTICKC,...,HORAIOPE,FECHAFOPE,HORAFOPE,IDPROTICKETS,FECHA,HORA,TIMESTAMP,TIMEIOPE,TIMEFOPE,TIMEDIF
0,PE00000001,057,CANOA CONFORT AL CORTE,EMPLANTILLADO,12.0,12.0,400.0,400.0,10003201001,1,...,17:40:16,2016-01-29,16:48:41,1,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:16,2016-01-29 16:48:41,23:08:25
1,PE00000001,057,CANOA CONFORT AL CORTE,MONTADOR,12.0,12.0,1400.0,1400.0,10003202001,1,...,17:40:16,2016-01-29,16:48:41,2,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:16,2016-01-29 16:48:41,23:08:25
2,PE00000001,057,CANOA CONFORT AL CORTE,COSTURA,12.0,12.0,450.0,450.0,10003203001,1,...,17:40:16,2016-01-29,16:48:41,3,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:16,2016-01-29 16:48:41,23:08:25
3,PE00000001,057,CANOA CONFORT AL CORTE,ARMADO,12.0,12.0,1200.0,1200.0,10003204001,1,...,17:40:16,2016-01-29,16:48:41,4,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:16,2016-01-29 16:48:41,23:08:25
4,PE00000001,057,CANOA CONFORT AL CORTE,CORTADO,12.0,12.0,200.0,200.0,10003205001,1,...,17:40:16,2016-01-29,16:48:41,5,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:16,2016-01-29 16:48:41,23:08:25
5,PE00000001,057,CANOA CONFORT AL CORTE,ESTAMPADO,12.0,12.0,200.0,200.0,10003206001,1,...,17:40:16,2016-01-29,16:48:41,6,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:16,2016-01-29 16:48:41,23:08:25
6,PE00000001,057,CANOA CONFORT AL CORTE,SELLOS,12.0,12.0,0.0,0.0,10003207001,1,...,17:40:16,2016-01-29,16:48:41,7,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:16,2016-01-29 16:48:41,23:08:25
7,PE00000001,057,CANOA CONFORT AL CORTE,FORRADO DE PLANTA,12.0,12.0,500.0,500.0,10003208001,1,...,17:40:16,2016-01-29,16:48:41,8,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:16,2016-01-29 16:48:41,23:08:25
8,PE00000001,057,CANOA CONFORT AL CORTE,PLANTILLAS,12.0,12.0,0.0,0.0,10003209001,1,...,17:40:16,2016-01-29,16:48:41,9,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:16,2016-01-29 16:48:41,23:08:25
9,PE00000001,057,CANOA CONFORT AL CORTE,EMPLANTILLADO,12.0,12.0,400.0,400.0,10003201002,2,...,17:40:11,2016-01-29,16:49:17,10,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:11,2016-01-29 16:49:17,23:09:06
10,PE00000001,057,CANOA CONFORT AL CORTE,MONTADOR,12.0,12.0,1400.0,1400.0,10003202002,2,...,17:40:11,2016-01-29,16:49:17,11,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:11,2016-01-29 16:49:17,23:09:06
11,PE00000001,057,CANOA CONFORT AL CORTE,COSTURA,12.0,12.0,450.0,450.0,10003203002,2,...,17:40:11,2016-01-29,16:49:17,12,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:11,2016-01-29 16:49:17,23:09:06
12,PE00000001,057,CANOA CONFORT AL CORTE,ARMADO,12.0,12.0,1200.0,1200.0,10003204002,2,...,17:40:11,2016-01-29,16:49:17,13,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:11,2016-01-29 16:49:17,23:09:06
13,PE00000001,057,CANOA CONFORT AL CORTE,CORTADO,12.0,12.0,200.0,200.0,10003205002,2,...,17:40:11,2016-01-29,16:49:17,14,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:11,2016-01-29 16:49:17,23:09:06
14,PE00000001,057,CANOA CONFORT AL CORTE,ESTAMPADO,12.0,12.0,200.0,200.0,10003206002,2,...,17:40:11,2016-01-29,16:49:17,15,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:11,2016-01-29 16:49:17,23:09:06
15,PE00000001,057,CANOA CONFORT AL CORTE,SELLOS,12.0,12.0,0.0,0.0,10003207002,2,...,17:40:11,2016-01-29,16:49:17,16,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:11,2016-01-29 16:49:17,23:09:06
16,PE00000001,057,CANOA CONFORT AL CORTE,FORRADO DE PLANTA,12.0,12.0,500.0,500.0,10003208002,2,...,17:40:11,2016-01-29,16:49:17,17,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:11,2016-01-29 16:49:17,23:09:06
17,PE00000001,057,CANOA CONFORT AL CORTE,PLANTILLAS,12.0,12.0,0.0,0.0,10003209002,2,...,17:40:11,2016-01-29,16:49:17,18,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:11,2016-01-29 16:49:17,23:09:06
18,PE00000001,057,CANOA CONFORT AL CORTE,EMPLANTILLADO,10.0,10.0,400.0,400.0,10003201003,3,...,17:41:23,2016-01-29,16:46:58,19,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:41:23,2016-01-29 16:46:58,23:05:35
19,PE00000001,057,CANOA CONFORT AL CORTE,MONTADOR,10.0,10.0,1400.0,1400.0,10003202003,3,...,17:41:23,2016-01-29,16:46:58,20,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:41:23,2016-01-29 16:46:58,23:05:35
20,PE00000001,057,CANOA CONFORT AL CORTE,COSTURA,10.0,10.0,450.0,450.0,10003203003,3,...,17:41:23,2016-01-29,16:46:58,21,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:41:23,2016-01-29 16:46:58,23:05:35
21,PE00000001,057,CANOA CONFORT AL CORTE,ARMADO,10.0,10.0,1200.0,1200.0,10003204003,3,...,17:41:23,2016-01-29,16:46:58,22,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:41:23,2016-01-29 16:46:58,23:05:35
22,PE00000001,057,CANOA CONFORT AL CORTE,CORTADO,10.0,10.0,200.0,200.0,10003205003,3,...,17:41:23,2016-01-29,16:46:58,23,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:41:23,2016-01-29 16:46:58,23:05:35
23,PE00000001,057,CANOA CONFORT AL CORTE,ESTAMPADO,10.0,10.0,200.0,200.0,10003206003,3,...,17:41:23,2016-01-29,16:46:58,24,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:41:23,2016-01-29 16:46:58,23:05:35
24,PE00000001,057,CANOA CONFORT AL CORTE,SELLOS,10.0,10.0,0.0,0.0,10003207003,3,...,17:41:23,2016-01-29,16:46:58,25,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:41:23,2016-01-29 16:46:58,23:05:35
25,PE00000001,057,CANOA CONFORT AL CORTE,FORRADO DE PLANTA,10.0,10.0,500.0,500.0,10003208003,3,...,17:41:23,2016-01-29,16:46:58,26,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:41:23,2016-01-29 16:46:58,23:05:35
26,PE00000001,057,CANOA CONFORT AL CORTE,PLANTILLAS,10.0,10.0,0.0,0.0,10003209003,3,...,17:41:23,2016-01-29,16:46:58,27,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:41:23,2016-01-29 16:46:58,23:05:35
27,PE00000002,154,CANOA CONFORT AL CORTE,EMPLANTILLADO,12.0,12.0,400.0,400.0,10003301001,4,...,17:38:49,2016-01-29,16:47:55,28,2016-01-25,11:04:32,2016-01-25 11:04:32,2016-01-28 17:38:49,2016-01-29 16:47:55,23:09:06
28,PE00000002,154,CANOA CONFORT AL CORTE,MONTADOR,12.0,12.0,1400.0,1400.0,10003302001,4,...,17:38:49,2016-01-29,16:47:55,29,2016-01-25,11:04:32,2016-01-25 11:04:32,2016-01-28 17:38:49,2016-01-29 16:47:55,23:09:06
29,PE00000002,154,CANOA CONFORT AL CORTE,COSTURA,12.0,12.0,450.0,450.0,10003303001,4,...,17:38:49,2016-01-29,16:47:55,30,2016-01-25,11:04:32,2016-01-25 11:04:32,2016-01-28 17:38:49,2016-01-29 16:47:55,23:09:06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113798,PE00002193,053,PLANA HERRAJE 2017,COSTURA,13.0,13.0,520.0,520.0,10747903008,15340,...,NaN,2008-01-01,NaN,113808,2017-10-13,15:10:10,2017-10-13 15:10:10,NaT,NaT,NaT
113799,PE00002193,053,PLANA HERRAJE 2017,ARMADO,13.0,13.0,1350.0,1350.0,10747904008,15340,...,NaN,2008-01-01,NaN,113809,2017-10-13,15:10:10,2017-10-13 15:10:10,NaT,NaT,NaT
113800,PE00002193,053,PLANA HERRAJE 2017,CORTADO,13.0,13.0,400.0,400.0,10747905008,15340,...,NaN,2008-01-01,NaN,113810,2017-10-13,15:10:10,2017-10-13 15:10:10,NaT,NaT,NaT
113801,PE00002193,053,PLANA HERRAJE 2017,SUELAS,13.0,13.0,200.0,200.0,10747906008,15340,...,NaN,2008-01-01,NaN,113811,2017-10-13,15:10:10,2017-10-13 15:10:10,NaT,NaT,NaT
113802,PE00002193,053,PLANA HERRAJE 2017,LASER,13.0,13.0,0.0,0.0,10747907008,15340,...,NaN,2008-01-01,NaN,113812,2017-10-13,15:10:10,2017-10-13 15:10:10,NaT,NaT,NaT
113803,PE00002193,053,PLANA HERRAJE 2017,PLANTILLAS,13.0,13.0,0.0,0.0,10747908008,15340,...,NaN,2008-01-01,NaN,113813,2017-10-13,15:10:10,2017-10-13 15:10:10,NaT,NaT,NaT
113804,PE00002193,053,PLANA HERRAJE 2017,EMPLANTILLADO,13.0,13.0,400.0,400.0,10747901009,15341,...,NaN,2008-01-01,NaN,113814,2017-10-13,15:10:10,2017-10-13 15:10:10,NaT,NaT,NaT
113805,PE00002193,053,PLANA HERRAJE 2017,MONTADOR,13.0,13.0,1450.0,1450.0,10747902009,15341,...,NaN,2008-01-01,NaN,113815,2017-10-13,15:10:10,2017-10-13 15:10:10,NaT,NaT,NaT
113806,PE00002193,053,PLANA HERRAJE 2017,COSTURA,13.0,13.0,520.0,520.0,10747903009,15341,...,NaN,2008-01-01,NaN,113816,2017-10-13,15:10:10,2017-10-13 15:10:10,NaT,NaT,NaT
113807,PE00002193,053,PLANA HERRAJE 2017,ARMADO,13.0,13.0,1350.0,1350.0,10747904009,15341,...,NaN,2008-01-01,NaN,113817,2017-10-13,15:10:11,2017-10-13 15:10:11,NaT,NaT,NaT
113808,PE00002193,053,PLANA HERRAJE 2017,CORTADO,13.0,13.0,400.0,400.0,10747905009,15341,...,NaN,2008-01-01,NaN,113818,2017-10-13,15:10:11,2017-10-13 15:10:11,NaT,NaT,NaT
113809,PE00002193,053,PLANA HERRAJE 2017,SUELAS,13.0,13.0,200.0,200.0,10747906009,15341,...,NaN,2008-01-01,NaN,113819,2017-10-13,15:10:11,2017-10-13 15:10:11,NaT,NaT,NaT
113810,PE00002193,053,PLANA HERRAJE 2017,LASER,13.0,13.0,0.0,0.0,10747907009,15341,...,NaN,2008-01-01,NaN,113820,2017-10-13,15:10:11,2017-10-13 15:10:11,NaT,NaT,NaT
113811,PE00002193,053,PLANA HERRAJE 2017,PLANTILLAS,13.0,13.0,0.0,0.0,10747908009,15341,...,NaN,2008-01-01,NaN,113821,2017-10-13,15:10:11,2017-10-13 15:10:11,NaT,NaT,NaT
113812,PE00002193,053,PLANA HERRAJE 2017,EMPLANTILLADO,13.0,13.0,400.0,400.0,10747901010,15342,...,NaN,2008-01-01,NaN,113822,2017-10-13,15:10:11,2017-10-13 15:10:11,NaT,NaT,NaT
113813,PE00002193,053,PLANA HERRAJE 2017,MONTADOR,13.0,13.0,1450.0,1450.0,10747902010,15342,...,NaN,2008-01-01,NaN,113823,2017-10-13,15:10:11,2017-10-13 15:10:11,NaT,NaT,NaT
113814,PE00002193,053,PLANA HERRAJE 2017,COSTURA,13.0,13.0,520.0,520.0,10747903010,15342,...,NaN,2008-01-01,NaN,113824,2017-10-13,15:10:11,2017-10-13 15:10:11,NaT,NaT,NaT
113815,PE00002193,053,PLANA HERRAJE 2017,ARMADO,13.0,13.0,1350.0,1350.0,10747904010,15342,...,NaN,2008-01-01,NaN,113825,2017-10-13,15:10:11,2017-10-13 15:10:11,NaT,NaT,NaT
113816,PE00002193,053,PLANA HERRAJE 2017,CORTADO,13.0,13.0,400.0,400.0,10747905010,15342,...,NaN,2008-01-01,NaN,113826,2017-10-13,15:10:12,2017-10-13 15:10:12,NaT,NaT,NaT
113817,PE00002193,053,PLANA HERRAJE 2017,SUELAS,13.0,13.0,200.0,200.0,10747906010,15342,...,NaN,2008-01-01,NaN,113827,2017-10-13,15:10:12,2017-10-13 15:10:12,NaT,NaT,NaT
113818,PE00002193,053,PLANA HERRAJE 2017,LASER,13.0,13.0,0.0,0.0,10747907010,15342,...,NaN,2008-01-01,NaN,113828,2017-10-13,15:10:12,2017-10-13 15:10:12,NaT,NaT,NaT
113819,PE00002193,053,PLANA HERRAJE 2017,PLANTILLAS,13.0,13.0,0.0,0.0,10747908010,15342,...,NaN,2008-01-01,NaN,113829,2017-10-13,15:10:12,2017-10-13 15:10:12,NaT,NaT,NaT
113820,PE00002193,053,LASER,EMPLANTILLADO,13.0,13.0,400.0,400.0,10747901011,15343,...,NaN,2008-01-01,NaN,113830,2017-10-13,15:10:12,2017-10-13 15:10:12,NaT,NaT,NaT
113821,PE00002193,053,LASER,MONTADOR,13.0,13.0,1450.0,1450.0,10747902011,15343,...,NaN,2008-01-01,NaN,113831,2017-10-13,15:10:12,2017-10-13 15:10:12,NaT,NaT,NaT
113822,PE00002193,053,LASER,COSTURA,13.0,13.0,520.0,520.0,10747903011,15343,...,NaN,2008-01-01,NaN,113832,2017-10-13,15:10:12,2017-10-13 15:10:12,NaT,NaT,NaT
113823,PE00002193,053,LASER,ARMADO,13.0,13.0,1250.0,1250.0,10747904011,15343,...,NaN,2008-01-01,NaN,113833,2017-10-13,15:10:12,2017-10-13 15:10:12,NaT,NaT,NaT
113824,PE00002193,053,LASER,CORTADO,13.0,13.0,400.0,400.0,10747905011,15343,...,NaN,2008-01-01,NaN,113834,2017-10-13,15:10:13,2017-10-13 15:10:13,NaT,NaT,NaT
113825,PE00002193,053,LASER,SUELAS,13.0,13.0,200.0,200.0,10747906011,15343,...,NaN,2008-01-01,NaN,113835,2017-10-13,15:10:13,2017-10-13 15:10:13,NaT,NaT,NaT
113826,PE00002193,053,LASER,PLANTILLAS,13.0,13.0,0.0,0.0,10747907011,15343,...,NaN,2008-01-01,NaN,113836,2017-10-13,15:10:13,2017-10-13 15:10:13,NaT,NaT,NaT
113827,PE00002193,053,LASER,LASER,13.0,13.0,0.0,0.0,10747908011,15343,...,NaN,2008-01-01,NaN,113837,2017-10-13,15:10:13,2017-10-13 15:10:13,NaT,NaT,NaT

### Buscamos cantidad de valores null en cada columna

Debido a que al tomar la diferencia entre Inicio y Fin de Operación tenemos valores nulos, buscamos cuántos valores nulos tiene cada columna

In [288]:
df.isnull().sum()

NROFAVE          1868
CODCLI           1868
CODPP               0
CODOPE              0
CANVEN              0
CANOPE              0
COSTOOPE            0
COSTOOPEC           0
TICKET              0
NROTICKC            0
FECHATICK           0
HORATICK         3835
FECHAITT            0
HORAITT         95797
FECHAFTT            0
HORAFTT         36968
FECHAIOPE           0
HORAIOPE        12431
FECHAFOPE           0
HORAFOPE        18296
IDPROTICKETS        0
FECHA               0
HORA                0
TIMESTAMP           0
TIMEIOPE        12431
TIMEFOPE        18296
TIMEDIF         18321
dtype: int64

### Agrupamos columnas buscando patrones

+ La intención es determinar el rendimiento de cada operador, por lo que analizar las columnas con registros de FECHA y HORA son una excelente base para este análisis
+ Buscamos las columnas que no tengan registros Nulos y contengan FECHA y/o HORA

In [289]:
df.loc[:,df.columns.str.contains("HORA|FECHA")].isnull().sum()

FECHATICK        0
HORATICK      3835
FECHAITT         0
HORAITT      95797
FECHAFTT         0
HORAFTT      36968
FECHAIOPE        0
HORAIOPE     12431
FECHAFOPE        0
HORAFOPE     18296
FECHA            0
HORA             0
dtype: int64

In [290]:
df.groupby('FECHATICK').count().head()

,NROFAVE,CODCLI,CODPP,CODOPE,CANVEN,CANOPE,COSTOOPE,COSTOOPEC,TICKET,NROTICKC,...,HORAIOPE,FECHAFOPE,HORAFOPE,IDPROTICKETS,FECHA,HORA,TIMESTAMP,TIMEIOPE,TIMEFOPE,TIMEDIF
FECHATICK,,,,,,,,,,,,,,,,,,,,,
2008-01-01,1967,1967,3835,3835,3835,3835,3835,3835,3835,3835,...,0,3835,0,3835,3835,3835,3835,0,0,0
2016-01-25,315,315,315,315,315,315,315,315,315,315,...,315,315,315,315,315,315,315,315,315,315
2016-01-28,54,54,54,54,54,54,54,54,54,54,...,54,54,54,54,54,54,54,54,54,54
2016-01-29,276,276,276,276,276,276,276,276,276,276,...,264,276,245,276,276,276,276,264,245,245
2016-02-01,572,572,572,572,572,572,572,572,572,572,...,447,572,426,572,572,572,572,447,426,426

In [291]:
df.groupby('FECHAITT').count().head()

,NROFAVE,CODCLI,CODPP,CODOPE,CANVEN,CANOPE,COSTOOPE,COSTOOPEC,TICKET,NROTICKC,...,HORAIOPE,FECHAFOPE,HORAFOPE,IDPROTICKETS,FECHA,HORA,TIMESTAMP,TIMEIOPE,TIMEFOPE,TIMEDIF
FECHAITT,,,,,,,,,,,,,,,,,,,,,
2008-01-01,93929,93929,95797,95797,95797,95797,95797,95797,95797,95797,...,83370,95797,78655,95797,95797,95797,95797,83370,78655,78634
2016-01-29,60,60,60,60,60,60,60,60,60,60,...,60,60,60,60,60,60,60,60,60,60
2016-01-30,9,9,9,9,9,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
2016-02-02,10,10,10,10,10,10,10,10,10,10,...,10,10,10,10,10,10,10,10,10,10
2016-02-08,137,137,137,137,137,137,137,137,137,137,...,137,137,136,137,137,137,137,137,136,136

In [292]:
df.groupby('FECHAFTT').count().head()

,NROFAVE,CODCLI,CODPP,CODOPE,CANVEN,CANOPE,COSTOOPE,COSTOOPEC,TICKET,NROTICKC,...,HORAIOPE,FECHAFOPE,HORAFOPE,IDPROTICKETS,FECHA,HORA,TIMESTAMP,TIMEIOPE,TIMEFOPE,TIMEDIF
FECHAFTT,,,,,,,,,,,,,,,,,,,,,
2008-01-01,34467,34467,36335,36335,36335,36335,36335,36335,36335,36335,...,23969,36335,20759,36335,36335,36335,36335,23969,20759,20751
2016-01-28,35,35,35,35,35,35,35,35,35,35,...,35,35,35,35,35,35,35,35,35,35
2016-01-29,119,119,119,119,119,119,119,119,119,119,...,119,119,119,119,119,119,119,119,119,119
2016-01-30,55,55,55,55,55,55,55,55,55,55,...,55,55,55,55,55,55,55,55,55,55
2016-02-02,14,14,14,14,14,14,14,14,14,14,...,14,14,14,14,14,14,14,14,14,14

In [293]:
df.groupby('FECHAIOPE').count().head()

,NROFAVE,CODCLI,CODPP,CODOPE,CANVEN,CANOPE,COSTOOPE,COSTOOPEC,TICKET,NROTICKC,...,HORAIOPE,FECHAFOPE,HORAFOPE,IDPROTICKETS,FECHA,HORA,TIMESTAMP,TIMEIOPE,TIMEFOPE,TIMEDIF
FECHAIOPE,,,,,,,,,,,,,,,,,,,,,
2008-01-01,10563,10563,12431,12431,12431,12431,12431,12431,12431,12431,...,0,12431,25,12431,12431,12431,12431,0,25,0
2016-01-28,315,315,315,315,315,315,315,315,315,315,...,315,315,315,315,315,315,315,315,315,315
2016-01-29,54,54,54,54,54,54,54,54,54,54,...,54,54,54,54,54,54,54,54,54,54
2016-02-08,522,522,522,522,522,522,522,522,522,522,...,522,522,516,522,522,522,522,522,516,516
2016-02-09,18,18,18,18,18,18,18,18,18,18,...,18,18,18,18,18,18,18,18,18,18

In [294]:
df.groupby('FECHAFOPE').count().head()

,NROFAVE,CODCLI,CODPP,CODOPE,CANVEN,CANOPE,COSTOOPE,COSTOOPEC,TICKET,NROTICKC,...,FECHAIOPE,HORAIOPE,HORAFOPE,IDPROTICKETS,FECHA,HORA,TIMESTAMP,TIMEIOPE,TIMEFOPE,TIMEDIF
FECHAFOPE,,,,,,,,,,,,,,,,,,,,,
2008-01-01,16428,16428,18296,18296,18296,18296,18296,18296,18296,18296,...,18296,5890,0,18296,18296,18296,18296,5890,0,0
2016-01-29,315,315,315,315,315,315,315,315,315,315,...,315,315,315,315,315,315,315,315,315,315
2016-02-08,72,72,72,72,72,72,72,72,72,72,...,72,72,72,72,72,72,72,72,72,72
2016-02-09,204,204,204,204,204,204,204,204,204,204,...,204,204,204,204,204,204,204,204,204,204
2016-02-10,222,222,222,222,222,222,222,222,222,222,...,222,222,222,222,222,222,222,222,222,222

Observamos que en todos los casos tenemos registros de **2008-01-01** por lo cual utilizar estas columnas para analizar el rendimiento de los operadores no es confiable, así pues descartamos los registros que contengan esta fecha en las columnas **FECHAIOPE** y **FECHAFOPE**

In [295]:
df_filtrado = df[(df['FECHAIOPE'] != '2008-01-01') & (df['FECHAFOPE'] != '2008-01-01')]
df_filtrado

,NROFAVE,CODCLI,CODPP,CODOPE,CANVEN,CANOPE,COSTOOPE,COSTOOPEC,TICKET,NROTICKC,...,HORAIOPE,FECHAFOPE,HORAFOPE,IDPROTICKETS,FECHA,HORA,TIMESTAMP,TIMEIOPE,TIMEFOPE,TIMEDIF
0,PE00000001,057,CANOA CONFORT AL CORTE,EMPLANTILLADO,12.0,12.0,400.0,400.0,10003201001,1,...,17:40:16,2016-01-29,16:48:41,1,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:16,2016-01-29 16:48:41,0 days 23:08:25
1,PE00000001,057,CANOA CONFORT AL CORTE,MONTADOR,12.0,12.0,1400.0,1400.0,10003202001,1,...,17:40:16,2016-01-29,16:48:41,2,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:16,2016-01-29 16:48:41,0 days 23:08:25
2,PE00000001,057,CANOA CONFORT AL CORTE,COSTURA,12.0,12.0,450.0,450.0,10003203001,1,...,17:40:16,2016-01-29,16:48:41,3,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:16,2016-01-29 16:48:41,0 days 23:08:25
3,PE00000001,057,CANOA CONFORT AL CORTE,ARMADO,12.0,12.0,1200.0,1200.0,10003204001,1,...,17:40:16,2016-01-29,16:48:41,4,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:16,2016-01-29 16:48:41,0 days 23:08:25
4,PE00000001,057,CANOA CONFORT AL CORTE,CORTADO,12.0,12.0,200.0,200.0,10003205001,1,...,17:40:16,2016-01-29,16:48:41,5,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:16,2016-01-29 16:48:41,0 days 23:08:25
5,PE00000001,057,CANOA CONFORT AL CORTE,ESTAMPADO,12.0,12.0,200.0,200.0,10003206001,1,...,17:40:16,2016-01-29,16:48:41,6,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:16,2016-01-29 16:48:41,0 days 23:08:25
6,PE00000001,057,CANOA CONFORT AL CORTE,SELLOS,12.0,12.0,0.0,0.0,10003207001,1,...,17:40:16,2016-01-29,16:48:41,7,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:16,2016-01-29 16:48:41,0 days 23:08:25
7,PE00000001,057,CANOA CONFORT AL CORTE,FORRADO DE PLANTA,12.0,12.0,500.0,500.0,10003208001,1,...,17:40:16,2016-01-29,16:48:41,8,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:16,2016-01-29 16:48:41,0 days 23:08:25
8,PE00000001,057,CANOA CONFORT AL CORTE,PLANTILLAS,12.0,12.0,0.0,0.0,10003209001,1,...,17:40:16,2016-01-29,16:48:41,9,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:16,2016-01-29 16:48:41,0 days 23:08:25
9,PE00000001,057,CANOA CONFORT AL CORTE,EMPLANTILLADO,12.0,12.0,400.0,400.0,10003201002,2,...,17:40:11,2016-01-29,16:49:17,10,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:11,2016-01-29 16:49:17,0 days 23:09:06
10,PE00000001,057,CANOA CONFORT AL CORTE,MONTADOR,12.0,12.0,1400.0,1400.0,10003202002,2,...,17:40:11,2016-01-29,16:49:17,11,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:11,2016-01-29 16:49:17,0 days 23:09:06
11,PE00000001,057,CANOA CONFORT AL CORTE,COSTURA,12.0,12.0,450.0,450.0,10003203002,2,...,17:40:11,2016-01-29,16:49:17,12,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:11,2016-01-29 16:49:17,0 days 23:09:06
12,PE00000001,057,CANOA CONFORT AL CORTE,ARMADO,12.0,12.0,1200.0,1200.0,10003204002,2,...,17:40:11,2016-01-29,16:49:17,13,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:11,2016-01-29 16:49:17,0 days 23:09:06
13,PE00000001,057,CANOA CONFORT AL CORTE,CORTADO,12.0,12.0,200.0,200.0,10003205002,2,...,17:40:11,2016-01-29,16:49:17,14,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:11,2016-01-29 16:49:17,0 days 23:09:06
14,PE00000001,057,CANOA CONFORT AL CORTE,ESTAMPADO,12.0,12.0,200.0,200.0,10003206002,2,...,17:40:11,2016-01-29,16:49:17,15,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:11,2016-01-29 16:49:17,0 days 23:09:06
15,PE00000001,057,CANOA CONFORT AL CORTE,SELLOS,12.0,12.0,0.0,0.0,10003207002,2,...,17:40:11,2016-01-29,16:49:17,16,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:11,2016-01-29 16:49:17,0 days 23:09:06
16,PE00000001,057,CANOA CONFORT AL CORTE,FORRADO DE PLANTA,12.0,12.0,500.0,500.0,10003208002,2,...,17:40:11,2016-01-29,16:49:17,17,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:11,2016-01-29 16:49:17,0 days 23:09:06
17,PE00000001,057,CANOA CONFORT AL CORTE,PLANTILLAS,12.0,12.0,0.0,0.0,10003209002,2,...,17:40:11,2016-01-29,16:49:17,18,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:40:11,2016-01-29 16:49:17,0 days 23:09:06
18,PE00000001,057,CANOA CONFORT AL CORTE,EMPLANTILLADO,10.0,10.0,400.0,400.0,10003201003,3,...,17:41:23,2016-01-29,16:46:58,19,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:41:23,2016-01-29 16:46:58,0 days 23:05:35
19,PE00000001,057,CANOA CONFORT AL CORTE,MONTADOR,10.0,10.0,1400.0,1400.0,10003202003,3,...,17:41:23,2016-01-29,16:46:58,20,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:41:23,2016-01-29 16:46:58,0 days 23:05:35
20,PE00000001,057,CANOA CONFORT AL CORTE,COSTURA,10.0,10.0,450.0,450.0,10003203003,3,...,17:41:23,2016-01-29,16:46:58,21,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:41:23,2016-01-29 16:46:58,0 days 23:05:35
21,PE00000001,057,CANOA CONFORT AL CORTE,ARMADO,10.0,10.0,1200.0,1200.0,10003204003,3,...,17:41:23,2016-01-29,16:46:58,22,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:41:23,2016-01-29 16:46:58,0 days 23:05:35
22,PE00000001,057,CANOA CONFORT AL CORTE,CORTADO,10.0,10.0,200.0,200.0,10003205003,3,...,17:41:23,2016-01-29,16:46:58,23,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:41:23,2016-01-29 16:46:58,0 days 23:05:35
23,PE00000001,057,CANOA CONFORT AL CORTE,ESTAMPADO,10.0,10.0,200.0,200.0,10003206003,3,...,17:41:23,2016-01-29,16:46:58,24,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:41:23,2016-01-29 16:46:58,0 days 23:05:35
24,PE00000001,057,CANOA CONFORT AL CORTE,SELLOS,10.0,10.0,0.0,0.0,10003207003,3,...,17:41:23,2016-01-29,16:46:58,25,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:41:23,2016-01-29 16:46:58,0 days 23:05:35
25,PE00000001,057,CANOA CONFORT AL CORTE,FORRADO DE PLANTA,10.0,10.0,500.0,500.0,10003208003,3,...,17:41:23,2016-01-29,16:46:58,26,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:41:23,2016-01-29 16:46:58,0 days 23:05:35
26,PE00000001,057,CANOA CONFORT AL CORTE,PLANTILLAS,10.0,10.0,0.0,0.0,10003209003,3,...,17:41:23,2016-01-29,16:46:58,27,2016-01-25,11:04:00,2016-01-25 11:04:00,2016-01-28 17:41:23,2016-01-29 16:46:58,0 days 23:05:35
27,PE00000002,154,CANOA CONFORT AL CORTE,EMPLANTILLADO,12.0,12.0,400.0,400.0,10003301001,4,...,17:38:49,2016-01-29,16:47:55,28,2016-01-25,11:04:32,2016-01-25 11:04:32,2016-01-28 17:38:49,2016-01-29 16:47:55,0 days 23:09:06
28,PE00000002,154,CANOA CONFORT AL CORTE,MONTADOR,12.0,12.0,1400.0,1400.0,10003302001,4,...,17:38:49,2016-01-29,16:47:55,29,2016-01-25,11:04:32,2016-01-25 11:04:32,2016-01-28 17:38:49,2016-01-29 16:47:55,0 days 23:09:06
29,PE00000002,154,CANOA CONFORT AL CORTE,COSTURA,12.0,12.0,450.0,450.0,10003303001,4,...,17:38:49,2016-01-29,16:47:55,30,2016-01-25,11:04:32,2016-01-25 11:04:32,2016-01-28 17:38:49,2016-01-29 16:47:55,0 days 23:09:06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110733,PE00002161,63338624-7,BORDADO,COSTURA,11.0,11.0,520.0,520.0,10737503003,14960,...,20:32:49,2017-10-14,09:21:36,110743,2017-10-07,09:55:22,2017-10-07 09:55:22,2017-10-09 20:32:49,2017-10-14 09:21:36,4 days 12:48:47
110734,PE00002161,63338624-7,BORDADO,ARMADO,11.0,11.0,1450.0,1450.0,10737504003,14960,...,20:32:49,2017-10-14,09:21:36,110744,2017-10-07,09:55:22,2017-10-07 09:55:22,2017-10-09 20:32:49,2017-10-14 09:21:36,4 days 12:48:47
110735,PE00002161,63338624-7,BORDADO,CORTADO,11.0,11.0,400.0,400.0,10737505003,14960,...,20:32:49,2017-10-14,09:21:36,110745,2017-10-07,09:55:22,2017-10-07 09:55:22,2017-10-09 20:32:49,2017-10-14 09:21:36,4 days 12:48:47
110736,PE00002161,63338624-7,BORDADO,BORDADO,11.0,11.0,0.0,0.0,10737506003,14960,...,20:32:49,2017-10-14,09:21:36,110746,2017-10-07,09:55:22,2017-10-07 09:55:22,2017-10-09 20:32:49,2017-10-14 09:21:36,4 days 12:48:47
110737,PE00002161,63338624-7,BORDADO,SUELAS,11.0,11.0,200.0,200.0,10737507003,14960,...,20:32:49,2017-10-14,09:21:36,110747,2017-10-07,09:55:22,2017-10-07 09:55:22,2017-10-09 20:32:49,2017-10-14 09:21:36,4 days 12:48:47
110738,PE00002161,63338624-7,BORDADO,PLANTILLAS,11.0,11.0,0.0,0.0,10737508003,14960,...,20:32:49,2017-10-14,09:21:36,110748,2017-10-07,09:55:22,2017-10-07 09:55:22,2017-10-09 20:32:49,2017-10-14 09:21:36,4 days 12:48:47
110763,PE00002161,63338624-7,CANOA 2017,EMPLANTILLADO,11.0,11.0,400.0,400.0,10737501007,14964,...,20:32:36,2017-10-14,15:41:05,110773,2017-10-07,09:55:25,2017-10-07 09:55:25,2017-10-09 20:32:36,2017-10-14 15:41:05,4 days 19:08:29
110764,PE00002161,63338624-7,CANOA 2017,MONTADOR,11.0,11.0,1950.0,1950.0,10737502007,14964,...,20:32:36,2017-10-14,15:41:05,110774,2017-10-07,09:55:25,2017-10-07 09:55:25,2017-10-09 20:32:36,2017-10-14 15:41:05,4 days 19:08:29
110765,PE00002161,63338624-7,CANOA 2017,COSTURA,11.0,11.0,520.0,520.0,10737503007,14964,...,20:32:36,2017-10-14,15:41:05,110775,2017-10-07,09:55:26,2017-10-07 09:55:26,2017-10-09 20:32:36,2017-10-14 15:41:05,4 days 19:08:29
110766,PE00002161,63338624-7,CANOA 2017,ARMADO,11.0,11.0,1250.0,1250.0,10737504007,14964,...,20:32:36,2017-10-14,15:41:05,110776,2017-10-07,09:55:26,2017-10-07 09:55:26,2017-10-09 20:32:36,2017-10-14 15:41:05,4 days 19:08:29
110767,PE00002161,63338624-7,CANOA 2017,CORTADO,11.0,11.0,400.0,400.0,10737505007,14964,...,20:32:36,2017-10-14,15:41:05,110777,2017-10-07,09:55:26,2017-10-07 09:55:26,2017-10-09 20:32:36,2017-10-14 15:41:05,4 days 19:08:29
110768,PE00002161,63338624-7,CANOA 2017,PLANTILLAS,11.0,11.0,0.0,0.0,10737506007,14964,...,20:32:36,2017-10-14,15:41:05,110778,2017-10-07,09:55:26,2017-10-07 09:55:26,2017-10-09 20:32:36,2017-10-14 15:41:05,4 days 19:08:29
110769,PE00002161,63338624-7,CANOA 2017,FORRADO DE PLANTA,11.0,11.0,0.0,0.0,10737507007,14964,...,20:32:36,2017-10-14,15:41:05,110779,2017-10-07,09:55:26,2017-10-07 09:55:26,2017-10-09 20:32:36,2017-10-14 15:41:05,4 days 19:08:29
110770,PE00002161,63338624-7,CANOA 2017,BORDADO,11.0,11.0,0.0,0.0,10737508007,14964,...,20:32:36,2017-10-14,15:41:05,110780,2017-10-07,09:55:26,2017-10-07 09:55:26,2017-10-09 20:32:36,2017-10-14 15:41:05,4 days 19:08:29
110787,PE00002161,63338624-7,PLANA HERRAJE 2017,EMPLANTILLADO,11.0,11.0,400.0,400.0,10737501010,14967,...,20:32:26,2017-10-14,15:49:38,110797,2017-10-07,09:55:28,2017-10-07 09:55:28,2017-10-09 20:32:26,2017-10-14 15:49:38,4 days 19:17:12
110788,PE00002161,63338624-7,PLANA HERRAJE 2017,MONTADOR,11.0,11.0,1450.0,1450.0,10737502010,14967,...,20:32:26,2017-10-14,15:49:38,110798,2017-10-07,09:55:28,2017-10-07 09:55:28,2017-10-09 20:32:26,2017-10-14 15:49:38,4 days 19:17:12
110789,PE00002161,63338624-7,PLANA HERRAJE 2017,COSTURA,11.0,11.0,520.0,520.0,10737503010,14967,...,20:32:26,2017-10-14,15:49:38,110799,2017-10-07,09:55:28,2017-10-07 09:55:28,2017-10-09 20:32:26,2017-10-14 15:49:38,4 days 19:17:12
110790,PE00002161,63338624-7,PLANA HERRAJE 2017,ARMADO,11.0,11.0,1350.0,1350.0,10737504010,14967,...,20:32:26,2017-10-14,15:49:38,110800,2017-10-07,09:55:28,2017-10-07 09:55:28,2017-10-09 20:32:26,2017-10-14 15:49:38,4 days 19:17:12
110791,PE00002161,63338624-7,PLANA HERRAJE 2017,CORTADO,11.0,11.0,400.0,400.0,10737505010,14967,...,20:32:26,2017-10-14,15:49:38,110801,2017-10-07,09:55:28,2017-10-07 09:55:28,2017-10-09 20:32:26,2017-10-14 15:49:38,4 days 19:17:12
110792,PE00002161,63338624-7,PLANA HERRAJE 2017,SUELAS,11.0,11.0,200.0,200.0,10737506010,14967,...,20:32:26,2017-10-14,15:49:38,110802,2017-10-07,09:55:28,2017-10-07 09:55:28,2017-10-09 20:32:26,2017-10-14 15:49:38,4 days 19:17:12
110793,PE00002161,63338624-7,PLANA HERRAJE 2017,LASER,11.0,11.0,0.0,0.0,10737507010,14967,...,20:32:26,2017-10-14,15:49:38,110803,2017-10-07,09:55:29,2017-10-07 09:55:29,2017-10-09 20:32:26,2017-10-14 15:49:38,4 days 19:17:12
110794,PE00002161,63338624-7,PLANA HERRAJE 2017,PLANTILLAS,11.0,11.0,0.0,0.0,10737508010,14967,...,20:32:26,2017-10-14,15:49:38,110804,2017-10-07,09:55:29,2017-10-07 09:55:29,2017-10-09 20:32:26,2017-10-14 15:49:38,4 days 19:17:12
112793,PE00002176,63338624-7,LASER,EMPLANTILLADO,13.0,13.0,400.0,400.0,10742301001,15216,...,11:45:58,2017-10-13,15:02:08,112803,2017-10-10,14:14:07,2017-10-10 14:14:07,2017-10-11 11:45:58,2017-10-13 15:02:08,2 days 03:16:10
112794,PE00002176,63338624-7,LASER,MONTADOR,13.0,13.0,1450.0,1450.0,10742302001,15216,...,11:45:58,2017-10-13,15:02:08,112804,2017-10-10,14:14:07,2017-10-10 14:14:07,2017-10-11 11:45:58,2017-10-13 15:02:08,2 days 03:16:10
112795,PE00002176,63338624-7,LASER,COSTURA,13.0,13.0,520.0,520.0,10742303001,15216,...,11:45:58,2017-10-13,15:02:08,112805,2017-10-10,14:14:07,2017-10-10 14:14:07,2017-10-11 11:45:58,2017-10-13 15:02:08,2 days 03:16:10
112796,PE00002176,63338624-7,LASER,ARMADO,13.0,13.0,1250.0,1250.0,10742304001,15216,...,11:45:58,2017-10-13,15:02:08,112806,2017-10-10,14:14:07,2017-10-10 14:14:07,2017-10-11 11:45:58,2017-10-13 15:02:08,2 days 03:16:10
112797,PE00002176,63338624-7,LASER,CORTADO,13.0,13.0,400.0,400.0,10742305001,15216,...,11:45:58,2017-10-13,15:02:08,112807,2017-10-10,14:14:07,2017-10-10 14:14:07,2017-10-11 11:45:58,2017-10-13 15:02:08,2 days 03:16:10
112798,PE00002176,63338624-7,LASER,SUELAS,13.0,13.0,200.0,200.0,10742306001,15216,...,11:45:58,2017-10-13,15:02:08,112808,2017-10-10,14:14:07,2017-10-10 14:14:07,2017-10-11 11:45:58,2017-10-13 15:02:08,2 days 03:16:10
112799,PE00002176,63338624-7,LASER,PLANTILLAS,13.0,13.0,0.0,0.0,10742307001,15216,...,11:45:58,2017-10-13,15:02:08,112809,2017-10-10,14:14:07,2017-10-10 14:14:07,2017-10-11 11:45:58,2017-10-13 15:02:08,2 days 03:16:10
112800,PE00002176,63338624-7,LASER,LASER,13.0,13.0,0.0,0.0,10742308001,15216,...,11:45:58,2017-10-13,15:02:08,112810,2017-10-10,14:14:07,2017-10-10 14:14:07,2017-10-11 11:45:58,2017-10-13 15:02:08,2 days 03:16:10

**IMPORTANTE: ** Al hacer este filtrado, perdemos el **16%** de los datos

In [296]:
1-float(len(df_filtrado))/float(len(original))

0.16095336823980044

### Rendimiento por tipo de Operador

In [316]:
df_filtrado.groupby(["CODOPE","NROTICKC","TIMEDIF"]).sum()

                                 CANVEN  CANOPE  COSTOOPE  COSTOOPEC  \
CODOPE NROTICKC TIMEDIF
ARMADO 1        0 days 23:08:25    12.0    12.0    1200.0     1200.0
       2        0 days 23:09:06    12.0    12.0    1200.0     1200.0
       3        0 days 23:05:35    10.0    10.0    1200.0     1200.0
       4        0 days 23:09:06    12.0    12.0    1200.0     1200.0
       5        0 days 23:08:23    12.0    12.0    1200.0     1200.0
       6        0 days 23:05:35    10.0    10.0    1200.0     1200.0
       7        0 days 23:08:51    12.0    12.0    1200.0     1200.0
       8        0 days 23:54:27    12.0    12.0    1200.0     1200.0
       9        0 days 23:05:34    10.0    10.0    1200.0     1200.0
       10       0 days 23:08:21    12.0    12.0    1200.0     1200.0
       11       0 days 23:08:44    12.0    12.0    1200.0     1200.0
       12       0 days 23:05:58    10.0    10.0    1200.0     1200.0
       13       0 days 23:07:59    12.0    12.0    1200.0     1200.0
       14       0 days 23:07:09    12.0    12.0    1200.0     1200.0
       15       0 days 23:06:06    10.0    10.0    1200.0     1200.0
       16       0 days 23:06:06    12.0    12.0    1200.0     1200.0
       17       0 days 23:06:13    12.0    12.0    1200.0     1200.0
       18       0 days 23:05:59    10.0    10.0    1200.0     1200.0
       19       0 days 23:06:13    12.0    12.0    1200.0     1200.0
       20       0 days 23:05:55    12.0    12.0    1200.0     1200.0
       21       0 days 23:06:20    10.0    10.0    1200.0     1200.0
       22       0 days 23:06:07    12.0    12.0    1200.0     1200.0
       23       0 days 23:06:12    12.0    12.0    1200.0     1200.0
       24       0 days 23:02:28    10.0    10.0    1200.0     1200.0
       25       0 days 23:05:29    12.0    12.0    1200.0     1200.0
       26       1 days 01:26:48    12.0    12.0    1200.0     1200.0
       27       0 days 23:06:10    12.0    12.0    1200.0     1200.0
       28       1 days 01:26:47    12.0    12.0    1200.0     1200.0
       29       1 days 01:26:30    12.0    12.0    1200.0     1200.0
       30       1 days 01:26:54    12.0    12.0    1200.0     1200.0
...                                 ...     ...       ...        ...
SUELAS 14836    5 days 16:44:19   200.0    10.0       0.0        0.0
       14837    5 days 16:12:30   200.0    10.0       0.0        0.0
       14838    6 days 18:06:27   200.0    10.0       0.0        0.0
       14839    6 days 17:24:43   200.0    10.0       0.0        0.0
       14840    6 days 18:39:18   200.0    10.0       0.0        0.0
       14841    5 days 15:59:05   200.0    10.0       0.0        0.0
       14842    6 days 16:51:51   200.0    10.0       0.0        0.0
       14846    6 days 18:30:40   200.0    10.0       0.0        0.0
       14847    6 days 19:32:23   200.0    10.0       0.0        0.0
       14848    6 days 17:02:03   200.0    10.0       0.0        0.0
       14849    6 days 16:45:18   200.0    10.0       0.0        0.0
       14850    6 days 16:37:50   200.0    10.0       0.0        0.0
       14851    6 days 17:31:23   200.0    10.0       0.0        0.0
       14852    6 days 18:35:32   200.0    10.0       0.0        0.0
       14853    7 days 18:08:11    12.0    12.0     200.0      200.0
       14854    6 days 17:44:14    12.0    12.0     200.0      200.0
       14855    7 days 00:39:48    12.0    12.0     200.0      200.0
       14856    7 days 18:19:28    11.0    11.0     200.0      200.0
       14857    7 days 00:52:37    11.0    11.0     200.0      200.0
       14861    4 days 18:54:59    12.0    12.0     200.0      200.0
       14865    4 days 18:54:28    12.0    12.0     200.0      200.0
       14879    4 days 19:29:51    12.0    12.0     200.0      200.0
       14885    4 days 18:54:00    12.0    12.0     200.0      200.0
       14888    4 days 19:51:08     8.0     8.0     200.0      200.0
       14889    4 days 18:59:39     8.0     8.0     200.0      200.0
       14958    4 days 10:47:33    11.0    11.0     200.0      200.0
       14959    3 days 22:39:03    11.0    11.0     200.0      200.0
       14960    4 days 12:48:47    11.0    11.0     200.0      200.0
       14967    4 days 19:17:12    11.0    11.0     200.0      200.0
       15216    2 days 03:16:10    13.0    13.0     200.0      200.0

                                      TICKET  IDPROTICKETS
CODOPE NROTICKC TIMEDIF
ARMADO 1        0 days 23:08:25  10003204001             4
       2        0 days 23:09:06  10003204002            13
       3        0 days 23:05:35  10003204003            22
       4        0 days 23:09:06  10003304001            31
       5        0 days 23:08:23  10003304002            40
       6        0 days 23:05:35  10003304003            49
       7        0 days 23:08:51  10003404001            58
       8        0 days 23:54:27  10003404002            67
       9        0 days 23:05:34  10003404003            76
       10       0 days 23:08:21  10003504001            85
       11       0 days 23:08:44  10003504002            94
       12       0 days 23:05:58  10003504003           103
       13       0 days 23:07:59  10003604001           112
       14       0 days 23:07:09  10003604002           121
       15       0 days 23:06:06  10003604003           130
       16       0 days 23:06:06  10003704001           139
       17       0 days 23:06:13  10003704002           148
       18       0 days 23:05:59  10003704003           157
       19       0 days 23:06:13  10003804001           166
       20       0 days 23:05:55  10003804002           175
       21       0 days 23:06:20  10003804003           184
       22       0 days 23:06:07  10003904001           193
       23       0 days 23:06:12  10003904002           202
       24       0 days 23:02:28  10003904003           211
       25       0 days 23:05:29  10004004001           220
       26       1 days 01:26:48  10004004002           229
       27       0 days 23:06:10  10004004003           238
       28       1 days 01:26:47  10004104001           247
       29       1 days 01:26:30  10004104002           256
       30       1 days 01:26:54  10004104003           265
...                                      ...           ...
SUELAS 14836    5 days 16:44:19  10730206004        109466
       14837    5 days 16:12:30  10730206005        109474
       14838    6 days 18:06:27  10730206006        109482
       14839    6 days 17:24:43  10730206007        109490
       14840    6 days 18:39:18  10730206008        109498
       14841    5 days 15:59:05  10730206009        109506
       14842    6 days 16:51:51  10730206010        109514
       14846    6 days 18:30:40  10730206014        109546
       14847    6 days 19:32:23  10730206015        109554
       14848    6 days 17:02:03  10730206016        109562
       14849    6 days 16:45:18  10730206017        109570
       14850    6 days 16:37:50  10730206018        109578
       14851    6 days 17:31:23  10730206019        109586
       14852    6 days 18:35:32  10730206020        109594
       14853    7 days 18:08:11  10730406001        109602
       14854    6 days 17:44:14  10730406002        109610
       14855    7 days 00:39:48  10730406003        109618
       14856    7 days 18:19:28  10731006001        109626
       14857    7 days 00:52:37  10731006002        109634
       14861    4 days 18:54:59  10730306004        109668
       14865    4 days 18:54:28  10730307008        109701
       14879    4 days 19:29:51  10730606004        109814
       14885    4 days 18:54:00  10730607010        109863
       14888    4 days 19:51:08  10730706003        109886
       14889    4 days 18:59:39  10730706004        109894
       14958    4 days 10:47:33  10737507001        110731
       14959    3 days 22:39:03  10737507002        110739
       14960    4 days 12:48:47  10737507003        110747
       14967    4 days 19:17:12  10737506010        110802
       15216    2 days 03:16:10  10742306001        112808

[95501 rows x 6 columns]

In [319]:
df_filtrado.groupby(["NROTICKC","TIMEDIF"]).sum()

,,CANVEN,CANOPE,COSTOOPE,COSTOOPEC,TICKET,IDPROTICKETS
NROTICKC,TIMEDIF,,,,,,
1,0 days 23:08:25,108.0,108.0,4350.0,4350.0,90028845009,45
2,0 days 23:09:06,108.0,108.0,4350.0,4350.0,90028845018,126
3,0 days 23:05:35,90.0,90.0,4350.0,4350.0,90028845027,207
4,0 days 23:09:06,108.0,108.0,4350.0,4350.0,90029745009,288
5,0 days 23:08:23,108.0,108.0,4350.0,4350.0,90029745018,369
6,0 days 23:05:35,90.0,90.0,4350.0,4350.0,90029745027,450
7,0 days 23:08:51,108.0,108.0,4350.0,4350.0,90030645009,531
8,0 days 23:54:27,108.0,108.0,4350.0,4350.0,90030645018,612
9,0 days 23:05:34,90.0,90.0,4350.0,4350.0,90030645027,693
10,0 days 23:08:21,108.0,108.0,4350.0,4350.0,90031545009,774
11,0 days 23:08:44,108.0,108.0,4350.0,4350.0,90031545018,855
12,0 days 23:05:58,90.0,90.0,4350.0,4350.0,90031545027,936
13,0 days 23:07:59,108.0,108.0,4350.0,4350.0,90032445009,1017
14,0 days 23:07:09,108.0,108.0,4350.0,4350.0,90032445018,1098
15,0 days 23:06:06,90.0,90.0,4350.0,4350.0,90032445027,1179
16,0 days 23:06:06,108.0,108.0,4350.0,4350.0,90033345009,1260
17,0 days 23:06:13,108.0,108.0,4350.0,4350.0,90033345018,1341
18,0 days 23:05:59,90.0,90.0,4350.0,4350.0,90033345027,1422
19,0 days 23:06:13,108.0,108.0,4350.0,4350.0,90034245009,1503
20,0 days 23:05:55,108.0,108.0,4350.0,4350.0,90034245018,1584
21,0 days 23:06:20,90.0,90.0,4350.0,4400.0,90034245027,1665
22,0 days 23:06:07,108.0,108.0,4350.0,4350.0,90035145009,1746
23,0 days 23:06:12,108.0,108.0,4350.0,4350.0,90035145018,1827
24,0 days 23:02:28,90.0,90.0,4350.0,4350.0,90035145027,1908
25,0 days 23:05:29,108.0,108.0,4350.0,4350.0,90036045009,1989
26,1 days 01:26:48,108.0,108.0,4350.0,4350.0,90036045018,2070
27,0 days 23:06:10,108.0,108.0,4350.0,4350.0,90036045027,2151
28,1 days 01:26:47,108.0,108.0,4350.0,4350.0,90036945009,2232
29,1 days 01:26:30,108.0,108.0,4350.0,4350.0,90036945018,2313
30,1 days 01:26:54,108.0,108.0,4350.0,4350.0,90036945027,2394
...,...,...,...,...,...,...,...
14879,4 days 19:29:51,96.0,96.0,4320.0,4320.0,85844836032,878500
14885,4 days 18:54:00,96.0,96.0,4420.0,4420.0,85844836080,878884
14886,4 days 19:26:12,64.0,64.0,4520.0,4520.0,85845636008,878948
14888,4 days 19:51:08,64.0,64.0,4320.0,4320.0,85845636024,879076
14889,4 days 18:59:39,64.0,64.0,4320.0,4320.0,85845636032,879140
14902,4 days 20:16:23,96.0,96.0,4520.0,4520.0,85848836032,879972
14940,3 days 19:34:45,192.0,192.0,4520.0,4520.0,85883236008,882452
14941,3 days 22:02:46,128.0,128.0,4520.0,4520.0,85883236016,882516
14942,3 days 17:34:30,80.0,80.0,4520.0,4520.0,85883236024,882580
14943,4 days 17:03:34,128.0,128.0,4520.0,4520.0,85884036008,882644
14944,3 days 19:59:12,96.0,96.0,4520.0,4520.0,85884036016,882708
14945,3 days 20:22:46,64.0,64.0,4520.0,4520.0,85884036024,882772
14946,3 days 22:02:35,128.0,128.0,4520.0,4520.0,85884836008,882836
14947,3 days 21:33:08,96.0,96.0,4520.0,4520.0,85884836016,882900
14948,3 days 19:37:05,64.0,64.0,4520.0,4520.0,85884836024,882964
14949,4 days 16:42:28,128.0,128.0,4520.0,4520.0,85885636008,883028
14950,4 days 11:11:39,96.0,96.0,4520.0,4520.0,85885636016,883092
14951,3 days 21:33:11,64.0,64.0,4520.0,4520.0,85885636024,883156
14952,3 days 22:40:26,128.0,128.0,4520.0,4520.0,85886436008,883220
14953,4 days 15:47:22,96.0,96.0,4520.0,4520.0,85886436016,883284
14954,4 days 18:55:39,64.0,64.0,4520.0,4520.0,85886436024,883348
14955,4 days 17:06:23,128.0,128.0,4520.0,4520.0,85887236008,883412
14956,4 days 17:03:46,96.0,96.0,4520.0,4520.0,85887236016,883476
14957,4 days 11:50:04,64.0,64.0,4520.0,4520.0,85887236024,883540
14958,4 days 10:47:33,88.0,88.0,4420.0,4420.0,85900036008,885828
14959,3 days 22:39:03,88.0,88.0,4420.0,4420.0,85900036016,885892
14960,4 days 12:48:47,88.0,88.0,4420.0,4420.0,85900036024,885956
14964,4 days 19:08:29,88.0,88.0,4520.0,4520.0,85900036056,886212
14967,4 days 19:17:12,88.0,88.0,4320.0,4320.0,85900036080,886404
15216,2 days 03:16:10,104.0,104.0,4220.0,4220.0,85938436008,902452